apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: logging
  displayName: Logging
  icon: /icons/destinations/logging.svg
spec:
  parameters:
    - name: verbosity
      label: Verbosity
      description: The log level
      type: enum
      validValues:
        - detailed
        - normal
        - basic
      default: detailed
  logs:
    exporters: |
      - logging:
          verbosity: {{ .verbosity }}
  metrics:
    exporters: |
      - logging:
          verbosity: {{ .verbosity }}
  traces:
    exporters: |
      - logging:
          verbosity: {{ .verbosity }}
