// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReceiver is an autogenerated mock type for the Receiver type
type MockReceiver[T interface{}] struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, event
func (_m *MockReceiver[T]) Send(ctx context.Context, event T) {
	_m.Called(ctx, event)
}

type mockConstructorTestingTNewMockReceiver interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockReceiver creates a new instance of MockReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockReceiver[T interface{}](t mockConstructorTestingTNewMockReceiver) *MockReceiver[T] {
	mock := &MockReceiver[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
