// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSubscriber is an autogenerated mock type for the Subscriber type
type MockSubscriber[T interface{}] struct {
	mock.Mock
}

// Channel provides a mock function with given fields:
func (_m *MockSubscriber[T]) Channel() <-chan T {
	ret := _m.Called()

	var r0 <-chan T
	if rf, ok := ret.Get(0).(func() <-chan T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan T)
		}
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *MockSubscriber[T]) Close() {
	_m.Called()
}

// Receive provides a mock function with given fields: event
func (_m *MockSubscriber[T]) Receive(event T) {
	_m.Called(event)
}

// NewMockSubscriber creates a new instance of MockSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriber[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriber[T] {
	mock := &MockSubscriber[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
