# filelog source containing both count_logs and extract_metric processors
apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
  name: file-count-extract-logs
spec:
  contentType: text/yaml
  sources:
  - type: file
    parameters:
      - name: file_path
        value:
          - /tmp/test.log
      - name: exclude_file_path
        value: []
      - name: log_type
        value: file
      - name: parse_format
        value: json
      - name: regex_pattern
        value: ""
      - name: multiline_line_start_pattern
        value: ""
      - name: encoding
        value: utf-8
      - name: start_at
        value: end
    processors:
      - type: count_logs
        parameters:
          - name: match
            value: "true"
          - name: metric_name
            value: custom.metric.count
          - name: metric_units
            value: '{logs}'
          - name: attributes
            value:
              status_code: body.status
          - name: interval
            value: 60
        disabled: false
      - type: extract_metric
        parameters:
          - name: match
            value: body.duration != nil
          - name: path
            value: body.duration
          - name: metric_name
            value: http.request.duration
          - name: metric_units
            value: 'ms'
          - name: attributes
            value:
              status_code: body.status
          - name: interval
            value: 60
        disabled: false
  destinations:
  - name: googlecloud
  selector:
    matchLabels:
      "configuration": file-count-extract-logs
