apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: map_to_enum_demo
  displayName: Map To Enum Processor Type
  description: This is a sample processor type that demonstrates the mapToEnum parameter type.
  icon: /icons/destinations/otlp.svg
  labels:
    category: Parse
spec:
  version: 0.0.1
  parameters:
    - name: map_to_enum_param
      label: Map to Enums Param
      type: mapToEnum
      description: The first of its kind.
      validValues:
        - trace
        - debug
        - info
        - warning
        - error
        - fatal
      default:
        info: info
      options:
        gridColumns: 12
        labels:
          key: Current severity value
          value: New severity value
  logs:
    processors: |
      - transform/logs:
          error_mode: ignore
          log_statements:            
            - context: log
              statements:
              {{ range $k, $v := .map_to_enum_param }}
              - set(body["{{ $k }}"], "{{ $v }}")
              {{ end }}
