apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: MacOS
  displayName: Mac OS
  icon: /public/bindplane-logo.png
  description: Log parser for MacOS
spec:
  extra: stuff
  # settings below take directly from stanza-plugins
  version: 0.0.2
  supportedPlatforms:
    - macos
  parameters:
    - name: enable_system_log
      label: System Logs
      description: Enable to collect MacOS system logs
      type: bool
      default: true
    - name: system_log_path
      label: System Log Path
      description: The absolute path to the System log
      type: string
      default: "/var/log/system.log"
      relevantIf:
        - name: enable_system_log
          operator: equals
          value: true
    - name: enable_install_log
      label: Install Logs
      description: Enable to collect MacOS install logs
      type: bool
      default: true
    - name: install_log_path
      label: Install Log Path
      description: The absolute path to the Install log
      type: string
      default: "/var/log/install.log"
      relevantIf:
        - name: enable_install_log
          operator: equals
          value: true
    - name: collection_interval_seconds
      label: Collection Interval
      type: int
      default: "30"
    - name: start_at
      label: Start At
      description: Start reading file from 'beginning' or 'end'
      type: enum
      validValues:
        - beginning
        - end
      default: end
  metrics:
    # receivers, processors, exporters, and extensions can all be specified
    receivers: |
      - hostmetrics:
          collection_interval: 1m
          scrapers:
            load:
  logs:
    receivers: |
      - plugin/macos:
          plugin:
            name: macos
          parameters:
          - name: enable_system_log
            value: {{ .enable_system_log }}
          - name: system_log_path
            value: {{ .system_log_path }}
          - name: enable_install_log
            value: {{ .enable_install_log }}
          - name: install_log_path
            value: {{ .install_log_path }}
          - name: start_at
            value: {{ .start_at }}
      - plugin/journald:
          plugin:
            name: journald
