// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemStore is an autogenerated mock type for the SystemStore type
type MockSystemStore struct {
	mock.Mock
}

// UpdateAllRollouts provides a mock function with given fields: ctx
func (_m *MockSystemStore) UpdateAllRollouts(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockSystemStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSystemStore creates a new instance of MockSystemStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSystemStore(t mockConstructorTestingTNewMockSystemStore) *MockSystemStore {
	mock := &MockSystemStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
