apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: apache_common
  displayName: Apache Common
  icon: /icons/sources/apache.svg
  description: Collect logs from Apache Common formatted log files.
spec:
  version: 0.0.1
  supportedPlatforms:
    - linux
    - windows
    - macos
  parameters:
    - name: file_path
      label: Access Log File Path(s)
      description: Path to apache common formatted log file.
      type: strings
      options:
        gridColumns: 12
      default: ["/var/log/apache2/access.log"]

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true

  logs:
    receivers: |
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/apache_common_logs.yaml
          parameters:
            start_at: {{ .start_at }}
            file_path:
              {{ range $fp := .file_path }}
              - '{{ $fp }}'
              {{ end }}
