apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: cassandra
  displayName: Cassandra
  icon: /icons/sources/cassandra.svg
  description: Collect metrics and logs from Cassandra.
spec:
  version: 0.0.1
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      type: bool
      default: true

    - name: address
      label: Address
      description: IP address or hostname to scrape for Cassandra metrics.
      type: string
      default: localhost
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: port
      label: Port
      description: Port to scrape for Cassandra metrics.
      type: int
      default: 7199
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: jar_path
      label: JMX Metrics Collection Jar Path
      description: Full path to the JMX metrics jar.
      type: string
      default: "/opt/opentelemetry-java-contrib-jmx-metrics.jar"
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    # Logs

    - name: enable_logs
      label: Enable Logs
      type: bool
      default: true

    - name: enable_system_logs
      label: System Logs
      type: bool
      default: true
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: system_log_path
      label: System Log Path(s)
      description: File paths to system logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - "/var/log/cassandra/system.log"
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_system_logs
          operator: equals
          value: true

    - name: enable_debug_logs
      label: Debug Logs
      type: bool
      default: true
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: debug_log_path
      label: Debug Log Path(s)
      description: File paths to debug logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - "/var/log/cassandra/debug.log"
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_debug_logs
          operator: equals
          value: true

    - name: enable_gc_logs
      label: Garbage Collection Logs
      type: bool
      default: true
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: gc_log_path
      label: GC Log Path(s)
      description: File paths to garbage collection logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - "/var/log/cassandra/gc.log"
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_gc_logs
          operator: equals
          value: true

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - jmx:
          jar_path: {{ .jar_path }}
          collection_interval: {{ .collection_interval }}s
          endpoint: {{ .address }}:{{ .port }}
          target_system: cassandra
          resource_attributes:
            cassandra.endpoint: {{ .address }}:{{ .port }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/apache_cassandra_logs.yaml
          parameters:
            start_at: {{ .start_at }}
            timezone: {{ .timezone }}

            enable_system_logs: {{ .enable_system_logs }}
            {{ if .enable_system_logs }}
            system_log_path:
              {{ range $fp := .system_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}

            enable_debug_logs: {{ .enable_debug_logs }}
            {{ if .enable_debug_logs }}
            debug_log_path:
              {{ range $fp := .debug_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}

            enable_gc_logs: {{ .enable_gc_logs }}
            {{ if .enable_gc_logs }}
            gc_log_path:
              {{ range $fp := .gc_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
