apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: ciscoasa
  displayName: Cisco ASA
  icon: /icons/sources/cisco.svg
  description: Receive syslog from Cisco ASA.
spec:
  version: 0.0.1
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_ip
      label: Listen Address
      description: An IP address for the agent to bind. Typically 0.0.0.0 for most configurations.
      type: string
      default: "0.0.0.0"

    - name: listen_port
      label: Listen Port
      description: A TCP port which the agent will listen for syslog messages.
      type: int
      default: 5140
  logs:
    receivers: |
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/cisco_asa_logs.yaml
          parameters:
            listen_port: {{ .listen_port }}
            listen_ip: {{ .listen_ip }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
