apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: file
  displayName: File
  icon: /icons/sources/file.svg
  description: Collect logs from generic log files.
spec:
  version: 0.0.2
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: file_path
      label: File Path(s)
      description: File or directory paths to tail for logs.
      options:
        gridColumns: 12
      type: strings
      default: []
      required: true

    - name: exclude_file_path
      label: Exclude File Path(s)
      description: File or directory paths to exclude.
      options:
        gridColumns: 12
      type: strings
      default: []

    - name: log_type
      label: Log Type
      description: A friendly name that will be added to each log entry as an attribute.
      type: string
      default: "file"

    - name: parse_format
      label: Parse Format
      description: Method to use when parsing. When regex is selected, 'Regex Pattern' must be set.
      type: enum
      default: none
      validValues:
        - none
        - json
        - regex

    - name: regex_pattern
      label: Regex Pattern
      description: The regex pattern used when parsing log entries.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: parse_format
          operator: equals
          value: "regex"

    - name: multiline_parsing
      label: Multiline Parsing
      description: Enable multiline parsing options. Either specifying a regex for where a log starts or ends.
      type: enum
      default: none
      validValues:
        - none
        - specify line start
        - specify line end

    - name: multiline_line_start_pattern
      label: Multiline Start Pattern
      description: Regex pattern that matches beginning of a log entry, for handling multiline logs.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: multiline_parsing
          operator: equals
          value: specify line start

    - name: multiline_line_end_pattern
      label: Multiline End Pattern
      description: Regex pattern that matches end of a log entry, useful for terminating parsing of multiline logs.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: multiline_parsing
          operator: equals
          value: specify line end

    - name: parse_timestamp
      label: Parse Timestamp
      description: Whether to parse the timestamp from the log entry.
      type: bool
      default: false
      relevantIf:
        - name: parse_format
          operator: notEquals
          value: none
      options:
        gridColumns: 12

    - name: timestamp_field
      label: Timestamp Field
      description: The field containing the timestamp in the log entry.
      type: string
      default: timestamp
      required: true
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none

    - name: parse_timestamp_format
      label: Timestamp Format
      description: The format of the timestamp in the log entry. Choose a common format, or specify a custom format.
      type: enum
      default: ISO8601
      validValues:
        - ISO8601
        - RFC3339
        - Epoch
        - Manual
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none

    - name: epoch_timestamp_format
      label: Epoch Layout
      description: The layout of the epoch-based timestamp.
      type: enum
      required: true
      validValues:
        - s
        - ms
        - us
        - ns
        - s.ms
        - s.us
        - s.ns
      default: s
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_timestamp_format
          operator: equals
          value: Epoch
        - name: parse_format
          operator: notEquals
          value: none
      documentation:
        - text: Supported Epoch Layouts
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/timestamp.md#parse-a-timestamp-using-an-epoch-layout

    - name: manual_timestamp_format
      label: Timestamp Layout
      description: The strptime layout of the timestamp.
      type: string
      required: true
      default: "%Y-%m-%dT%H:%M:%S.%f%z"
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_timestamp_format
          operator: equals
          value: Manual
        - name: parse_format
          operator: notEquals
          value: none
      documentation:
        - text: Supported Layout Directives
          url: https://github.com/observiq/ctimefmt/blob/3e07deba22cf7a753f197ef33892023052f26614/ctimefmt.go#L63

    - name: parse_severity
      label: Parse Severity
      description: Whether to parse severity from the log entry.
      type: bool
      default: false
      relevantIf:
        - name: parse_format
          operator: notEquals
          value: none
      options:
        gridColumns: 12

    - name: severity_field
      label: Severity Field
      description: The field containing the severity in the log entry.
      type: string
      default: severity
      required: true
      relevantIf:
        - name: parse_severity
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none

    - name: include_file_name_attribute
      label: Include File Name Attribute
      description: Whether to add the file name as the attribute "log.file.name".
      type: bool
      default: true
      advancedConfig: true

    - name: include_file_path_attribute
      label: Include File Path Attribute
      description: Whether to add the file path as the attribute "log.file.path".
      type: bool
      default: false
      advancedConfig: true

    - name: include_file_name_resolved_attribute
      label: Include File Name Resolved Attribute
      description: Whether to add the file name after symlinks resolution as the attribute "log.file.name_resolved".
      type: bool
      default: false
      advancedConfig: true

    - name: include_file_path_resolved_attribute
      label: Include File Path Resolved Attribute
      description: Whether to add the file path after symlinks resolution as the attribute "log.file.path_resolved".
      type: bool
      default: false
      advancedConfig: true

    - name: encoding
      label: Encoding
      description: The encoding of the file being read.
      type: enum
      default: utf-8
      validValues:
        - nop
        - utf-8
        - utf-16le
        - utf-16be
        - ascii
        - big5
      advancedConfig: true

    - name: poll_interval
      label: Filesystem Poll Interval
      description: The duration of time in milliseconds between filesystem polls.
      type: int
      default: 200
      advancedConfig: true

    - name: max_concurrent_files
      label: Max Concurrent Files
      description: The maximum number of log files from which logs will be read concurrently. If the number of files matched exceeds this number, then files will be processed in batches.
      type: int
      default: 1024
      advancedConfig: true

    - name: parse_to
      label: Parse To
      description: The field to which the log will be parsed.
      type: enum
      validValues:
        - body
        - attributes
      default: body
      advancedConfig: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true

    - name: fingerprint_size
      label: Fingerprint size
      description: The size of the file fingerprint used to distinguish unique files.
      type: string
      default: 1kb
      advancedConfig: true

    - name: enable_offset_storage
      label: Enable File Offset Storage
      description: When enabled, the current position into a file will be saved to disk, and reading will resume from where it left off after a collector restart.
      type: bool
      default: true
      advancedConfig: true
      required: false
      options:
        sectionHeader: true

    - name: offset_storage_dir
      label: Offset Storage Directory
      description: The directory that the offset storage file will be created.
      type: string
      default: $OIQ_OTEL_COLLECTOR_HOME/storage
      advancedConfig: true
      relevantIf:
        - name: enable_offset_storage
          operator: equals
          value: true

    # Retry on failure
    - name: retry_on_failure_enabled
      label: Enable Retry on Failure
      description: Attempt to resend telemetry data that has failed to be transmitted to the destination.
      type: bool
      documentation:
        - text: Read More
          url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      # For the filelog receiver, the default is false. Enabling this enables backpressure, but the batch processor is still
      # an issue: https://github.com/open-telemetry/opentelemetry-collector/issues/7460
      default: false
      options:
        sectionHeader: true
      advancedConfig: true
      required: false

    - name: retry_on_failure_initial_interval
      label: Initial interval
      description: Time (in seconds) to wait after the first failure before retrying.
      type: int
      default: 1
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    - name: retry_on_failure_max_interval
      label: Max interval
      description: The upper bound (in seconds) on backoff.
      type: int
      default: 30
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    - name: retry_on_failure_max_elapsed_time
      label: Max elapsed time
      description: The maximum amount of time (in seconds) spent trying to send a batch, used to avoid a never-ending retry loop.
      type: int
      default: 300
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

  logs:
    extensions: |
      {{ if .enable_offset_storage }}
      - file_storage:
          directory: {{ .offset_storage_dir }}
          compaction:
            on_rebound: true
            directory: {{ .offset_storage_dir }}
      {{ end }}

    receivers: |
      - filelog:
          include:
          {{ range $fp := .file_path }}
            - '{{ $fp }}'
          {{ end }}
          {{ if .exclude_file_path }}
          exclude:
          {{ range $fp := .exclude_file_path }}
          - '{{ $fp }}'
          {{end}}
          {{ end }}
          {{ if ne .multiline_parsing "none"}}
          multiline:
            {{ if eq .multiline_parsing "specify line start" }}
            line_start_pattern: {{ .multiline_line_start_pattern | quote }}
            {{ end }}
            {{ if eq .multiline_parsing "specify line end" }}
            line_end_pattern: {{ .multiline_line_end_pattern | quote }}
            {{ end }}
          {{ end }}
          fingerprint_size: {{ .fingerprint_size }}
          encoding: {{ .encoding }}
          include_file_name: {{ .include_file_name_attribute }}
          include_file_name_resolved: {{ .include_file_name_resolved_attribute }}
          include_file_path: {{ .include_file_path_attribute }}
          include_file_path_resolved: {{ .include_file_path_resolved_attribute }}
          start_at: {{ .start_at }}
          poll_interval: {{ .poll_interval }}ms
          {{ if .enable_offset_storage }}
          storage: {{ bpComponentID "file_storage" }}
          {{ end }}
          max_concurrent_files: {{ .max_concurrent_files }}
          {{ bpRenderOtelRetryOnFailureConfig .retry_on_failure_enabled .retry_on_failure_initial_interval .retry_on_failure_max_interval .retry_on_failure_max_elapsed_time }} 
          operators:
            {{ if eq .parse_format "json" }}
            - type: json_parser
              parse_to: {{ .parse_to }}
            {{ if .parse_timestamp }}
              timestamp:
                parse_from: {{ .parse_to }}.{{ .timestamp_field }}
                {{ if eq .parse_timestamp_format "ISO8601" }}layout: '%Y-%m-%dT%H:%M:%S.%f%z'{{ end }}
                {{ if eq .parse_timestamp_format "RFC3339" }}layout: '%Y-%m-%dT%H:%M:%S.%f'{{ end }}
                {{ if eq .parse_timestamp_format "Manual" }}layout: '{{ .manual_timestamp_format }}'{{ end }}
                {{ if eq .parse_timestamp_format "Epoch" }}
                layout_type: epoch
                layout: {{ .epoch_timestamp_format }}
                {{ end }}
            {{ end }}
            {{ if .parse_severity }}
              severity:
                parse_from: {{ .parse_to }}.{{ .severity_field }}
            {{ end }}
            {{ end }}
            {{ if eq .parse_format "regex" }}
            - type: regex_parser
              regex: {{ .regex_pattern | quote }}
              parse_to: {{ .parse_to }}
            {{ if .parse_timestamp }}
              timestamp:
                parse_from: {{ .parse_to }}.{{ .timestamp_field }}
                {{ if eq .parse_timestamp_format "ISO8601" }}layout: '%Y-%m-%dT%H:%M:%S.%f%z'{{ end }}
                {{ if eq .parse_timestamp_format "RFC3339" }}layout: '%Y-%m-%dT%H:%M:%S.%f'{{ end }}
                {{ if eq .parse_timestamp_format "Manual" }}layout: '{{ .manual_timestamp_format }}'{{ end }}
                {{ if eq .parse_timestamp_format "Epoch" }}
                layout_type: epoch
                layout: {{ .epoch_timestamp_format }}
                {{ end }}
            {{ end }}
            {{ if .parse_severity }}
              severity:
                parse_from: {{ .parse_to }}.{{ .severity_field }}
            {{ end }}
            {{ end }}
            - type: add
              field: attributes.log_type
              value: {{ .log_type }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
