apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: haproxy
  displayName: HAProxy
  icon: /icons/sources/haproxy.svg
  description: Collect logs from HAProxy.
spec:
  version: 0.0.1
  supportedPlatforms:
    - linux
    - windows
    - macos
  parameters:
    - name: file_path
      label: File Path(s)
      description: File paths to tail for logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - /var/log/haproxy/haproxy.log

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true

  logs:
    receivers: |
      - plugin/haproxy:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/haproxy_logs.yaml
          parameters:
            start_at: {{ .start_at }}
            file_path:
              {{ range $fp := .file_path }}
              - '{{ $fp }}'
              {{ end }}
            timezone: {{ .timezone }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
