apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: iis
  displayName: Microsoft IIS
  icon: /icons/sources/microsoft_iis.svg
  description: Collect metrics and logs from Microsoft IIS.
spec:
  version: 0.0.2
  supported_platforms:
    - windows
  parameters:
    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      description: Enable to send metrics.
      type: bool
      default: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: disable_metrics
      label: Metrics
      description: Toggle the metrics you wish to collect on and off.
      type: metrics
      options:
        metricCategories:
          - label: Connection
            metrics:
              - name: iis.connection.active
              - name: iis.connection.anonymous
              - name: iis.connection.attempt.count
          - label: Network
            column: 1
            metrics:
              - name: iis.network.blocked
              - name: iis.network.file.count
              - name: iis.network.io
          - label: Request
            column: 1
            metrics:
              - name: iis.request.count
              - name: iis.request.queue.age.max
              - name: iis.request.queue.count
              - name: iis.request.rejected
          - label: Thread
            metrics:
              - name: iis.thread.active
          - label: Uptime
            metrics:
              - name: iis.uptime
      default: []
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    # Logs

    - name: enable_logs
      label: Enable Logs
      description: Enable to send logs.
      type: bool
      default: true

    - name: file_path
      label: File Path(s)
      description: File or directory paths to tail for logs.
      type: strings
      options:
        gridColumns: 12
      default: ["C:/inetpub/logs/LogFiles/W3SVC*/**/*.log"]
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: exclude_file_log_path
      label: Exclude File Path(s)
      description: File or directory paths to exclude.
      type: strings
      options:
        gridColumns: 12
      default: []
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: timezone
      label: Timezone
      description: RFC3164 only. The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: parse_to
      label: Parse To
      description: Parse structured log parts to either body or attributes.
      type: enum
      validValues:
        - body
        - attributes
      default: body
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - iis:
          collection_interval: {{ .collection_interval }}s
          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}
      {{ end }}

    processors: |
      {{ if .enable_metrics }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/iis_logs.yaml
          parameters:
            file_path:
              {{ range $fp := .file_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ if .exclude_file_log_path }}
            exclude_file_log_path:
              {{ range $fp := .exclude_file_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}
            timezone: {{ .timezone }}
            parse_to: {{ .parse_to }}
      {{ end }}

    processors: |
      {{ if .enable_logs }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}
