apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: jvm
  displayName: JVM
  icon: /icons/sources/jvm.svg
  description: Collect metrics from Java Virtual Machine via JMX.

spec:
  version: 0.0.1
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: address
      label: Address
      description: IP address or hostname to scrape for JMX metrics.
      type: string
      default: localhost

    - name: port
      label: Port
      description: Port to scrape for JMX metrics.
      type: int
      default: 9999

    - name: jar_path
      label: JMX Metrics Collection Jar Path
      description: Full path to the JMX metrics jar.
      type: string
      default: "/opt/opentelemetry-java-contrib-jmx-metrics.jar"
      advancedConfig: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true

  metrics:
    receivers: |
      - jmx:
          jar_path: {{ .jar_path }}
          collection_interval: {{ .collection_interval }}s
          endpoint: {{ .address }}:{{ .port }}
          target_system: jvm
          resource_attributes:
            jmx.endpoint: {{ .address }}:{{ .port }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
