apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: mongodb
  displayName: MongoDB
  icon: /icons/sources/mongodb.svg
  description: Collect metrics and logs from MongoDB.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      description: Enable to collect metrics.
      type: bool
      default: true

    - name: hosts
      label: Hosts
      description: |
        List of host:port or unix domain socket endpoints.
        Standalone deployments: the hostname and port of the mongod instance.
        Replica sets: the hostnames and ports of the mongod instances in the replica set configuration.
        Sharded deployments: a list of the mongos hosts.
      type: strings
      options:
        gridColumns: 12
      required: false
      default:
        - "localhost:27017"
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: disable_metrics
      label: Filtering
      type: metrics
      advancedConfig: true
      default: []
      options:
        metricCategories:
          - label: MongoDB Metrics
            metrics:
              - name: mongodb.cache.operations
              - name: mongodb.collection.count
              - name: mongodb.connection.count
              - name: mongodb.cursor.count
              - name: mongodb.cursor.timeout.count
              - name: mongodb.data.size
              - name: mongodb.database.count
              - name: mongodb.document.operation.count
              - name: mongodb.extent.count
              - name: mongodb.global_lock.time
              - name: mongodb.index.access.count
              - name: mongodb.index.count
              - name: mongodb.index.size
              - name: mongodb.memory.usage
              - name: mongodb.network.io.receive
              - name: mongodb.network.io.transmit
              - name: mongodb.network.request.count
              - name: mongodb.object.count
              - name: mongodb.operation.count
              - name: mongodb.operation.time
              - name: mongodb.session.count
              - name: mongodb.storage.size

    - name: username
      label: Username
      description: If authentication is required, specify a username with "clusterMonitor" permission.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: password
      label: Password
      description: The password user's password.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true
      options:
        password: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    # Metrics TLS Settings #

    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    # Logging
    #
    - name: enable_logs
      label: Enable Logs
      description: Enable to collect logs.
      type: bool
      default: true

    - name: log_paths
      label: Log Paths
      description: Path to Mongodb log file(s).
      type: strings
      options:
        gridColumns: 12
      default:
        - "/var/log/mongodb/mongodb.log*"
        - "/var/log/mongodb/mongod.log*"
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

    - name: parse_to
      label: Parse To
      description: Parse structured log parts to either body or attributes.
      type: enum
      validValues:
        - body
        - attributes
      default: body
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - mongodb:
          hosts:
            {{ range $host := .hosts }}
            - endpoint: {{ $host }}
            {{end}}
          username: {{ .username }}
          password: {{ .password }}
          collection_interval: {{ .collection_interval }}s
          tls:
          {{ if .enable_tls }}
            insecure: false
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
          {{ else }}
            insecure: true
          {{ end }}

          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}

      {{ end }}

    processors: |
      {{ if .enable_metrics }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin/mongodb:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/mongodb_logs.yaml
          parameters:
            log_paths:
            {{ range $fp := .log_paths }}
            - '{{ $fp }}'
            {{end}}
            start_at: {{ .start_at }}
            parse_to: {{ .parse_to }}
      {{ end }}

    processors: |
      {{ if .enable_logs }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}
