apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: otlp
  displayName: OpenTelemetry (OTLP)
  icon: /icons/destinations/otlp.svg
  description: Receive metrics, logs, and traces from OTLP exporters.
spec:
  version: 0.0.1
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_address
      label: Listen Address
      description: The IP address to listen on.
      type: string
      default: "0.0.0.0"

    - name: grpc_port
      label: GRPC Port
      description: TCP port to receive OTLP telemetry using the gRPC protocol. The port used must not be the same as the HTTP port. Set to 0 to disable.
      type: int
      default: 4317

    - name: http_port
      label: HTTP Port
      description: TCP port to receive OTLP telemetry using the HTTP protocol. The port used must not be the same as the gRPC port. Set to 0 to disable.
      type: int
      default: 4318

    # TLS
    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: cert_file
      label: Server Certificate File
      description: A path to the server certificate to be used for TLS.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Server Private Key
      description: A path to the server private key to be used for TLS.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: mutual_tls
      label: Mutual TLS
      description: Whether or not to require client TLS authentication (mTLS).
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: Certificate Authority
      description: A path to the certificate authority to use for authenticating client certificates.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

  logs+metrics+traces:
    receivers: |
      - otlp:
          protocols:
            {{ if .grpc_port }}
            grpc:
              endpoint: {{ .listen_address }}:{{ .grpc_port }}
              {{ if .enable_tls }}
              tls:
                cert_file: "{{ .cert_file }}"
                key_file: "{{ .key_file }}"
                {{ if .mutual_tls }}
                ca_file: "{{ .ca_file }}"
                {{ end }}
              {{ end }}
            {{ end }}

            {{ if .http_port }}
            http:
              endpoint: {{ .listen_address }}:{{ .http_port }}
              {{ if .enable_tls }}
              tls:
                cert_file: "{{ .cert_file }}"
                key_file: "{{ .key_file }}"
                {{ if .mutual_tls }}
                ca_file: "{{ .ca_file }}"
                {{ end }}
              {{ end }}
            {{ end }}
