apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: prometheus
  displayName: Prometheus
  icon: /icons/sources/prometheus.svg
  description: Collect metrics from Prometheus exporters.
spec:
  version: 0.1.0
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: static_targets
      label: Targets
      description: List of endpoints to scrape.
      type: strings
      default: []
      required: true

    - name: job_name
      label: Job Name
      description: The name of the scraper job. Will be set as service.name resource label.
      type: string
      default: ""
      required: true

    - name: enable_tls
      label: Enable TLS
      description: Whether to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: TLS Client Certificate File
      description: A TLS certificate used for client authentication, if TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: TLS Client Private Key File
      description: A TLS private key used for client authentication, if TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true

  metrics:
    receivers: |
      - prometheus:
          config:
            scrape_configs:
              - job_name: '{{ .job_name }}'
                scrape_interval: {{ .collection_interval }}s
                static_configs:
                  - targets:
                      {{ range $target := .static_targets }}
                      - {{ $target }}
                      {{end}}
                {{ if .enable_tls }}
                scheme: https
                tls_config:
                  insecure_skip_verify: {{ .insecure_skip_verify }}
                  ca_file: {{ .ca_file }}
                  cert_file: {{ .cert_file }}
                  key_file: {{ .key_file }}
                {{ end }}
