apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: redis
  displayName: Redis
  icon: /icons/sources/redis.svg
  description: Collect metrics and logs from Redis.
spec:
  version: 0.0.1
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      description: Enable to collect metrics.
      type: bool
      default: true

    - name: endpoint
      label: Endpoint
      description: The endpoint of the Redis server.
      type: string
      default: "localhost:6379"
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: transport
      label: Transport
      description: The transport protocol being used to connect to Redis.
      type: enum
      validValues:
        - tcp
        - unix
      default: tcp
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: disable_metrics
      label: Filtering
      type: metrics
      advancedConfig: true
      default: []
      options:
        metricCategories:
          - label: Client
            column: 0
            metrics:
              - name: redis.clients.blocked
              - name: redis.clients.connected
              - name: redis.clients.max_input_buffer
              - name: redis.clients.max_output_buffer
          - label: Commands
            column: 1
            metrics:
              - name: redis.cmd.calls
              - name: redis.cmd.usec
              - name: redis.commands
              - name: redis.commands.processed
          - label: Connections
            column: 0
            metrics:
              - name: redis.connections.received
              - name: redis.connections.rejected
          - label: Database
            column: 1
            metrics:
              - name: redis.db.avg_ttl
              - name: redis.db.expires
              - name: redis.db.keys
          - label: Keys
            metrics:
              - name: redis.keys.evicted
              - name: redis.keys.expired
              - name: redis.keyspace.hits
              - name: redis.keyspace.misses
          - label: Memory
            column: 0
            metrics:
              - name: redis.maxmemory
              - name: redis.memory.fragmentation_ratio
              - name: redis.memory.lua
              - name: redis.memory.peak
              - name: redis.memory.rss
              - name: redis.memory.used
          - label: Network
            column: 1
            metrics:
              - name: redis.net.input
              - name: redis.net.output
          - label: Replication
            column: 0
            metrics:
              - name: redis.replication.backlog_first_byte_offset
              - name: redis.replication.offset
              - name: redis.role
              - name: redis.slaves.connected
          - label: System
            column: 1
            metrics:
              - name: redis.cpu.time
              - name: redis.latest_fork
              - name: redis.rdb.changes_since_last_save
              - name: redis.uptime

    - name: password
      label: Password
      description: The password used to access the Redis instance; must match the password specified in the requirepass server configuration option.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true
      options:
        password: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    # Metrics TLS Settings #

    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    # Logging
    #
    - name: enable_logs
      label: Enable Logs
      description: Enable to collect logs.
      type: bool
      default: true

    - name: file_path
      label: Log Paths
      description: Path to Redis log file(s).
      type: strings
      options:
        gridColumns: 12
      default:
        # Default log path on Ubuntu / Debian
        - "/var/log/redis/redis-server.log"
        # Default log path built from src (6379 is the default redis port)
        - "/var/log/redis_6379.log"
        # Default log path on CentOS / RHEL
        - "/var/log/redis/redis.log"
        # Default log path on SLES
        - "/var/log/redis/default.log"
        # Default log path from one click installer (6379 is the default redis port)
        - "/var/log/redis/redis_6379.log"
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - redis:
          endpoint: {{ .endpoint }}
          transport: {{ .transport }}
          password: {{ .password }}
          collection_interval: {{ .collection_interval }}s
          tls:
          {{ if .enable_tls }}
            insecure: false
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
          {{ else }}
            insecure: true
          {{ end }}

          {{ if .disable_metrics }}
          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}
          {{ end }}

      {{ end }}

    processors: |
      {{ if .enable_metrics }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin/redis:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/redis_logs.yaml
          parameters:
            file_path:
            {{ range $fp := .file_path }}
            - '{{ $fp }}'
            {{end}}
            start_at: {{ .start_at }}
      {{ end }}

    processors: |
      {{ if .enable_logs }}
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}
