apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: netweaver
  displayName: SAP Netweaver
  icon: /icons/sources/sap.svg
  description: Collect metrics from SAP Netweaver.
spec:
  version: 0.0.1
  supported_platforms:
    - linux
  parameters:
    - name: hostname
      label: Hostname
      description: The hostname or IP address of the SAP Netweaver system.
      type: string
      default: localhost
      required: true

    - name: port
      label: Port
      description: The TCP port of the SAP Netweaver system.
      type: int
      default: 50013

    - name: username
      label: Username
      description: The username to use when connecting to SAP Netweaver.
      type: string
      required: true
      default: ""

    - name: password
      label: Password
      description: The password to use when connecting to SAP Netweaver.
      type: string
      required: true
      default: ""

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true

    - name: profile
      label: Profile
      description: The profile path in the form of /sapmnt/SID/profile/SID_INSTANCE_HOSTNAME to collect optional rfc and session count metrics.
      type: string
      default: ""
      options:
        sectionHeader: true
      advancedConfig: true
      documentation:
        - text: Read more
          url: https://help.sap.com/docs/SAP_NETWEAVER_750/b17bd20044a44edb9aa7830ee52ffac3/00fabccaa98348f291f3c7f02098116b.html

    - name: disable_metrics
      description: Toggle the metrics you wish to collect on and off.
      type: metrics
      default: []
      options:
        metricCategories:
          - label: Availability
            column: 0
            metrics:
              - name: sapnetweaver.system.instance_availability
              - name: sapnetweaver.process_availability
              - name: sapnetweaver.abap.update.status
              - name: sapnetweaver.certificate.validity
          - label: Work Process
            column: 0
            metrics:
              - name: sapnetweaver.work_process.active.count
              - name: sapnetweaver.work_process.job.aborted.count
          - label: CPU
            column: 0
            metrics:
              - name: sapnetweaver.cpu.utilization
              - name: sapnetweaver.cpu.system.utilization
          - label: Memory
            column: 0
            metrics:
              - name: sapnetweaver.memory.swap_space.utilization
              - name: sapnetweaver.host.memory.virtual.swap
              - name: sapnetweaver.memory.configured
              - name: sapnetweaver.memory.free
              - name: sapnetweaver.host.memory.virtual.overhead
          - label: Database
            column: 0
            metrics:
              - name: sapnetweaver.database.dialog.request.time
          - label: Session
            column: 0
            metrics:
              - name: sapnetweaver.sessions.http.count
              - name: sapnetweaver.sessions.security.count
              - name: sapnetweaver.sessions.browser.count
              - name: sapnetweaver.sessions.web.count
              - name: sapnetweaver.sessions.ejb.count
              - name: sapnetweaver.session.count
              - name: sapnetweaver.abap.rfc.count
              - name: sapnetweaver.abap.session.count
          - label: Request
            column: 1
            metrics:
              - name: sapnetweaver.request.count
              - name: sapnetweaver.request.timeout.count
              - name: sapnetweaver.response.duration
              - name: sapnetweaver.spool.request.error.count
              - name: sapnetweaver.host.spool_list.utilization
          - label: Queue
            column: 1
            metrics:
              - name: sapnetweaver.queue.count
              - name: sapnetweaver.queue_peak.count
              - name: sapnetweaver.queue_max.count
              - name: sapnetweaver.locks.enqueue.current.count
              - name: sapnetweaver.locks.enqueue.high.count
              - name: sapnetweaver.locks.enqueue.max.count
              - name: sapnetweaver.locks.enqueue.lock_time
              - name: sapnetweaver.locks.enqueue.lock_wait_time
              - name: sapnetweaver.locks.enqueue.errors.count
              - name: sapnetweaver.locks.dequeue.errors.count
          - label: Connection
            column: 1
            metrics:
              - name: sapnetweaver.connection.error.count
          - label: Cache
            column: 1
            metrics:
              - name: sapnetweaver.cache.hits
              - name: sapnetweaver.cache.evictions
          - label: Short Dumps
            column: 1
            metrics:
              - name: sapnetweaver.short_dumps.rate
      advancedConfig: true

    # Metrics TLS Settings #
    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true


  metrics:
    receivers: |
      - sapnetweaver:
          collection_interval: {{ .collection_interval }}s
          {{ if .enable_tls }}
          endpoint: https://{{ .hostname }}:{{ .port }}
          {{ else }}
          endpoint: http://{{ .hostname }}:{{ .port }}
          {{ end }}
          username: '{{ .username }}'
          password: '{{ .password }}'
          {{ if .profile }}
          profile: '{{ .profile }}'
          {{ end }}
          tls:
          {{ if .enable_tls }}
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
          {{ end }}
          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}
