apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: sqlserver
  displayName: Microsoft SQL Server
  icon: /icons/sources/sqlserver.svg
  description: Collect metrics and logs from Microsoft SQL Server.
spec:
  version: 0.0.1
  supportedPlatforms:
    - windows
  parameters:
    # Metrics
    #
    - name: enable_metrics
      label: Enable Metrics
      description: Enable to collect metrics.
      type: bool
      default: true

    - name: disable_metrics
      label: Metric Filtering
      type: metrics
      default: []
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

      options:
        metricCategories:
          - label: Batch
            column: 1
            metrics:
              - name: sqlserver.batch.request.rate
              - name: sqlserver.batch.sql_compilation.rate
              - name: sqlserver.batch.sql_recompilation.rate
          - label: Lock
            metrics:
              - name: sqlserver.lock.wait.rate
              - name: sqlserver.lock.wait_time.avg
          - label: Page
            column: 1
            metrics:
              - name: sqlserver.page.buffer_cache.hit_ratio
              - name: sqlserver.page.checkpoint.flush.rate
              - name: sqlserver.page.lazy_write.rate
              - name: sqlserver.page.life_expectancy
              - name: sqlserver.page.operation.rate
              - name: sqlserver.page.split.rate
          - label: Transaction
            metrics:
              - name: sqlserver.transaction.rate
              - name: sqlserver.transaction.write.rate
              - name: sqlserver.transaction_log.flush.data.rate
              - name: sqlserver.transaction_log.flush.rate
              - name: sqlserver.transaction_log.flush.wait.rate
              - name: sqlserver.transaction_log.growth.count
              - name: sqlserver.transaction_log.shrink.count
              - name: sqlserver.transaction_log.usage
          - label: User
            metrics:
              - name: sqlserver.user.connection.count

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    # Logging
    #
    - name: enable_logs
      label: Enable Logs
      description: Enable to collect logs.
      type: bool
      default: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - sqlserver:
          collection_interval: {{ .collection_interval }}s
      {{ end }}
          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/sql_server_logs.yaml
          parameters:
            start_at: {{ .start_at }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
