apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: syslog
  displayName: Syslog
  icon: /icons/sources/network.svg
  description: Receive syslog from network devices.
spec:
  version: 0.1.0
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_ip
      label: Listening IP Address
      description: The IP address to bind to and receive syslog.
      type: string
      required: true
      default: "0.0.0.0"

    - name: listen_port
      label: Listening Port
      description: The port to bind to and receive syslog. Collector must be running as root (Linux) or Administrator (windows) when binding to a port below 1024.
      type: int
      default: 5140
      required: true

    - name: protocol
      label: Protocol
      description: The RFC protocol to use when parsing incoming syslog.
      type: enum
      default: "rfc3164"
      validValues:
        - rfc3164
        - rfc5424
      required: true

    - name: connection_type
      label: Transport Protocol
      description: The transport protocol to use.
      type: enum
      default: udp
      validValues:
        - udp
        - tcp

    - name: data_flow
      label: Data Flow
      description: Enable high flow or reduced low flow.
      type: enum
      default: high
      validValues:
        - high
        - low

    - name: timezone
      label: Timezone
      description: RFC3164 only. The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true

    - name: parse_to
      label: Parse To
      description: Parse structured log parts to either body or attributes.
      type: enum
      validValues:
        - body
        - attributes
      default: body
      advancedConfig: true

    - name: enable_octet_counting
      label: Enable Octet Counting
      description: |
        Whether or not to enable RFC 6587 Octet Counting on syslog framing. This framing allows for the transmission of all characters inside a syslog message.
        This is incompatible with enabling usage of a non-transparent framing trailers.
      type: bool
      default: false
      required: false
      relevantIf:
        - name: connection_type
          operator: equals
          value: tcp
        - name: protocol
          operator: equals
          value: rfc5424
        - name: enable_non_transparent_framing_trailer
          operator: equals
          value: false
      advancedConfig: true
      options:
        # less jumpy configuration when selecting things
        gridColumns: 12
        # shows description for bools
        sectionHeader: true

    - name: enable_non_transparent_framing_trailer
      label: Enable Non-Transparent Framing Trailer
      description: |
        Whether or not to parse using a trailer character. This is a special character that will be the termination character for syslog messages.
        This is incompatible with enabling octet counting.
      type: bool
      default: false
      required: false
      relevantIf:
        - name: connection_type
          operator: equals
          value: tcp
        - name: protocol
          operator: equals
          value: rfc5424
        - name: enable_octet_counting
          operator: equals
          value: false
      advancedConfig: true
      options:
        gridColumns: 12
        sectionHeader: true

    - name: non_transparent_framing_trailer
      label: Non-Transparent Framing Trailer
      description: The framing trailer when using RFC 6587 Non-Transparent-Framing.
      default: LF
      type: enum
      required: false
      validValues:
        - LF
        - NUL
      relevantIf:
        - name: enable_non_transparent_framing_trailer
          operator: equals
          value: true
        - name: connection_type
          operator: equals
          value: tcp
      advancedConfig: true
      options:
        gridColumns: 12

    - name: enable_mutual_tls
      label: Enable Mutual TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      relevantIf:
        - name: connection_type
          operator: equals
          value: "tcp"
      advancedConfig: true
      # this gives more of an impression that the Enable TLS portion is its own section
      options:
        gridColumns: 12

    - name: cert_file
      label: TLS Certificate File
      description: Path to the x509 PEM certificate.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: TLS Private Key File
      description: Path to the x509 PEM private key.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: When set, enforces mutual TLS authentication and verifies client certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: tls_min_version
      label: Minimum TLS Version
      description: The minimum TLS version to support. 1.0 and 1.1 should not be considered secure.
      type: enum
      default: "1.2"
      validValues:
        - "1.3"
        - "1.2"
        - "1.1"
        - "1.0"
      relevantIf:
        - name: enable_mutual_tls
          operator: equals
          value: true
      advancedConfig: true

  logs:
    receivers: |
      - syslog:
          '{{ .connection_type }}': 
            listen_address: '{{ .listen_ip }}:{{ .listen_port }}'
            {{ if .enable_mutual_tls }}
            tls:
              {{ if .cert_file }}cert_file: '{{ .cert_file }}' {{ end }}
              {{ if .key_file }}key_file: '{{ .key_file }}'{{ end }}
              {{ if .ca_file }}ca_file: '{{ .ca_file }}'{{ end }}
              min_version: {{ .tls_min_version }}
            {{ end }}
          location: {{ .timezone }}
          protocol: {{ .protocol }}
          {{ if and (eq .connection_type "tcp") (eq .protocol "rfc5424") }}
          enable_octet_counting: {{ .enable_octet_counting }}
          {{ end }}
          {{ if and (.enable_non_transparent_framing_trailer) (eq .connection_type "tcp") (eq .protocol "rfc5424")}}
          non_transparent_framing_trailer: {{ .non_transparent_framing_trailer }}
          {{ end}}
          operators:
          {{ if eq .data_flow "low" }}
            - type: filter
              expr: 'attributes.priority != nil && attributes.priority % 8 == 7'
            - type: retain
              fields:
                - attributes.hostname
                - attributes.appname
                - attributes.msg_id
                - attributes.structured_data
                - attributes.version
          {{ end }}
          {{ if eq .parse_to "body" }}
            # Move all retained attributes to the body
            - id: move_appname
              type: move
              if: "attributes.appname != nil"
              from: attributes.appname
              to: body.appname
            - id: move_facility
              type: move
              if: "attributes.facility != nil"
              from: attributes.facility
              to: body.facility
            - id: move_hostname
              type: move
              if: "attributes.hostname != nil"
              from: attributes.hostname
              to: body.hostname
            - id: move_message
              type: move
              if: "attributes.message != nil"
              from: attributes.message
              to: body.message
            - id: move_msg_id
              type: move
              if: "attributes.msg_id != nil"
              from: attributes.msg_id
              to: body.msg_id
            - id: move_priority
              type: move
              if: "attributes.priority != nil"
              from: attributes.priority
              to: body.priority
            - id: move_proc_id
              type: move
              if: "attributes.proc_id != nil"
              from: attributes.proc_id
              to: body.proc_id
            - id: move_severity
              type: move
              if: "attributes.severity != nil"
              from: attributes.severity
              to: body.severity
            - id: move_structured_data
              type: move
              if: "attributes.structured_data != nil"
              from: attributes.structured_data
              to: body.structured_data
            - id: move_timestamp
              type: move
              if: "attributes.timestamp != nil"
              from: attributes.timestamp
              to: body.timestamp
            - id: move_version
              type: move
              if: "attributes.version != nil"
              from: attributes.version
              to: body.version
          {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
