apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: udp
  displayName: UDP Logs
  icon: /icons/sources/network.svg
  description: Receive logs from network devices via UDP.
spec:
  version: 0.0.1
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_ip
      label: Listen Address
      description: IP Address to listen on.
      type: string
      default: "0.0.0.0"

    - name: listen_port
      label: Listen Port
      description: Port to listen on.
      type: int
      required: true

  logs:
    receivers: |
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/udp_logs.yaml
          parameters:
            listen_port: {{ .listen_port }}
            listen_ip: {{ .listen_ip }}
            add_attributes: true

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
