apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: udp
  displayName: UDP Logs
  icon: /icons/sources/network.svg
  description: Receive logs from network devices via UDP.
spec:
  version: 0.1.0
  supportedPlatforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_ip
      label: Listen Address
      description: IP Address to listen on.
      type: string
      default: "0.0.0.0"

    - name: listen_port
      label: Listen Port
      description: Port to listen on.
      type: int
      required: true

    - name: log_type
      label: Log Type
      description: Arbitrary for attribute 'log_type'. Useful for filtering between many tcp sources.
      type: string
      default: udp

    - name: parse_format
      label: Parse Format
      description: Method to use when parsing. When regex is selected, 'Regex Pattern' must be set.
      type: enum
      default: none
      validValues:
        - none
        - json
        - regex

    - name: regex_pattern
      label: Regex Pattern
      description: The regex pattern used when parsing log entries.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: parse_format
          operator: equals
          value: "regex"

    - name: parse_timestamp
      label: Parse Timestamp
      description: Whether to parse the timestamp from the log entry.
      type: bool
      default: false
      relevantIf:
        - name: parse_format
          operator: notEquals
          value: none
      options:
        gridColumns: 12

    - name: timestamp_field
      label: Timestamp Field
      description: The field containing the timestamp in the log entry.
      type: string
      default: timestamp
      required: true
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none

    - name: parse_timestamp_format
      label: Timestamp Format
      description: The format of the timestamp in the log entry. Choose a common format, or specify a custom format.
      type: enum
      default: RFC3339
      validValues:
        - RFC3339
        - ISO8601
        - Epoch
        - Manual
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none

    - name: epoch_timestamp_format
      label: Epoch Layout
      description: The layout of the epoch-based timestamp.
      type: enum
      required: true
      validValues:
        - s
        - ms
        - us
        - ns
        - s.ms
        - s.us
        - s.ns
      default: s
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_timestamp_format
          operator: equals
          value: Epoch
        - name: parse_format
          operator: notEquals
          value: none
      documentation:
        - text: Supported Epoch Layouts
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/timestamp.md#parse-a-timestamp-using-an-epoch-layout

    - name: manual_timestamp_format
      label: Timestamp Layout
      description: The strptime layout of the timestamp.
      type: string
      required: true
      default: "%Y-%m-%dT%H:%M:%S.%f%z"
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_timestamp_format
          operator: equals
          value: Manual
        - name: parse_format
          operator: notEquals
          value: none
      documentation:
        - text: Supported Layout Directives
          url: https://github.com/observiq/ctimefmt/blob/3e07deba22cf7a753f197ef33892023052f26614/ctimefmt.go#L63

    - name: timezone
      label: Timezone
      description: The timezone to use if Timestamp Format doesn't include a timezone. Otherwise, the timezone in Timestamp Format will be respected.
      type: timezone
      default: "UTC"
      relevantIf:
        - name: parse_timestamp
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none
        - name: parse_timestamp_format
          operator: notEquals
          value: RFC3339
        - name: parse_timestamp_format
          operator: notEquals
          value: Epoch

    - name: parse_severity
      label: Parse Severity
      description: Whether to parse severity from the log entry.
      type: bool
      default: false
      relevantIf:
        - name: parse_format
          operator: notEquals
          value: none
      options:
        gridColumns: 12

    - name: severity_field
      label: Severity Field
      description: The field containing the severity in the log entry.
      type: string
      default: severity
      required: true
      relevantIf:
        - name: parse_severity
          operator: equals
          value: true
        - name: parse_format
          operator: notEquals
          value: none

    - name: parse_to
      label: Parse To
      description: The field to which the log will be parsed.
      type: enum
      validValues:
        - body
        - attributes
      default: body
      advancedConfig: true
      relevantIf:
        - name: parse_format
          operator: notEquals
          value: none

  logs:
    receivers: |
      - udplog:
          listen_address: {{ .listen_ip }}:{{ .listen_port }}
          add_attributes: true
          operators:
            {{ if ne .parse_format "none" }}
            - {{ bpRenderStandardParsingOperator .parse_format .parse_to .regex_pattern .parse_timestamp .timestamp_field .timezone .parse_timestamp_format .epoch_timestamp_format .manual_timestamp_format .parse_severity .severity_field }}
            {{ end }}
            - type: add
              field: attributes.log_type
              value: {{ .log_type }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
