apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: vmware_vcenter
  displayName: VMware vCenter
  icon: /icons/sources/vmware_vcenter.svg
  description: Collect metrics and receive syslog from VMware vCenter.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      description: Enable to send metrics.
      type: bool
      default: true
      options:
        gridColumns: 12

    - name: hostname
      label: Hostname
      description: The hostname or IP address of the vCenter system.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: port
      label: Port
      description: The TCP port of the vCenter system.
      type: int
      default: 443
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: username
      label: Username
      description: The username to use when connecting to vCenter.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: password
      label: Password
      description: The password to use when connecting to vCenter.
      type: string
      default: ""
      required: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      options:
        password: true

    - name: collection_interval
      label: Collection Interval
      description: How often (minutes) to scrape for metrics.
      type: int
      default: 2
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: metrics_strict_tls_verify
      label: Strict TLS Certificate Verification
      description: Enable to require TLS certificate verification.
      type: bool
      default: false
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      options:
        gridColumns: 12
        sectionHeader: true

    - name: metrics_ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates. Not required if the collector's operating system already trusts the certificate authority.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: metrics_strict_tls_verify
          operator: equals
          value: true
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: metrics_mutual_tls
      label: Mutual TLS Authentication
      description: Enable to require TLS mutual authentication.
      type: bool
      default: false
      relevantIf:
        - name: metrics_strict_tls_verify
          operator: equals
          value: true
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: metrics_mtls_cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication, if mutual TLS is enabled.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: metrics_strict_tls_verify
          operator: equals
          value: true
        - name: metrics_mutual_tls
          operator: equals
          value: true
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: metrics_mtls_key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication, if mutual TLS is enabled.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: metrics_strict_tls_verify
          operator: equals
          value: true
        - name: metrics_mutual_tls
          operator: equals
          value: true
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    - name: disable_metrics
      label: Metrics
      description: Toggle the metrics you wish to collect on and off.
      type: metrics
      options:
        metricCategories:
          - label: Cluster
            column: 0
            metrics:
              - name: vcenter.cluster.cpu.effective
              - name: vcenter.cluster.cpu.limit
              - name: vcenter.cluster.host.count
              - name: vcenter.cluster.memory.effective
              - name: vcenter.cluster.memory.limit
              - name: vcenter.cluster.memory.used
              - name: vcenter.cluster.vm.count

          - label: Host
            column: 0
            metrics:
              - name: vcenter.host.cpu.usage
              - name: vcenter.host.cpu.utilization
              - name: vcenter.host.disk.latency.avg
              - name: vcenter.host.disk.latency.max
              - name: vcenter.host.disk.throughput
              - name: vcenter.host.memory.usage
              - name: vcenter.host.memory.utilization
              - name: vcenter.host.network.packet.count
              - name: vcenter.host.network.packet.errors
              - name: vcenter.host.network.throughput
              - name: vcenter.host.network.usage

          - label: Datastore
            column: 1
            metrics:
              - name: vcenter.datastore.disk.usage
              - name: vcenter.datastore.disk.utilization

          - label: Resource
            column: 1
            metrics:
              - name: vcenter.resource_pool.cpu.shares
              - name: vcenter.resource_pool.cpu.usage
              - name: vcenter.resource_pool.memory.shares
              - name: vcenter.resource_pool.memory.usage

          - label: VM Memory
            column: 1
            metrics:
              - name: vcenter.vm.memory.ballooned
              - name: vcenter.vm.memory.usage
          - label: VM Disk
            column: 1
            metrics:
              - name: vcenter.vm.disk.latency.avg
              - name: vcenter.vm.disk.latency.max
              - name: vcenter.vm.disk.throughput
              - name: vcenter.vm.disk.usage
              - name: vcenter.vm.disk.utilization

          - label: VM Network
            column: 1
            metrics:
              - name: vcenter.vm.network.packet.count
      default: []
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
      advancedConfig: true

    # Logging
    - name: enable_logs
      label: Enable Logs
      description: Enable to collect vCenter logs.
      type: bool
      default: true
      options:
        gridColumns: 12

    - name: listen_ip
      label: Listening IP Address
      description: The IP address to bind to and receive syslog.
      type: string
      default: "0.0.0.0"
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: listen_port
      label: Listening Port
      description: The port to bind to and receive syslog. Collector must be running as root (Linux) or Administrator (windows) when binding to a port below 1024.
      type: int
      default: 5140
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: enable_tls_logs
      label: Enable TLS
      description: Whether or not to use TLS when receiving incoming syslog.
      type: bool
      default: false
      advancedConfig: true
      options:
        gridColumns: 12
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: parse_to
      label: Parse To
      description: Parse structured log parts to either body or attributes.
      type: enum
      validValues:
        - body
        - attributes
      default: body
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
      advancedConfig: true

    - name: logs_cert_file
      label: TLS Certificate File
      description: Path to the x509 PEM certificate.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_tls_logs
          operator: equals
          value: true
      advancedConfig: true

    - name: logs_key_file
      label: TLS Private Key File
      description: Path to the x509 PEM private key.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_tls_logs
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - vcenter:
          endpoint: https://{{ .hostname }}:{{ .port }}
          username: {{ .username }}
          password: {{ .password }}
          collection_interval: {{ .collection_interval }}m
          tls:
            insecure: false
            {{ if .metrics_strict_tls_verify }}
            insecure_skip_verify: false
            {{ if .metrics_ca_file }}
            ca_file: {{ .metrics_ca_file }}
            {{ end }}
            {{ else }}
            insecure_skip_verify: true
            {{ end }}
            {{ if .metrics_mutual_tls }}
            cert_file: "{{ .metrics_mtls_cert_file }}"
            key_file: "{{ .metrics_mtls_key_file }}"
            {{ end }}

          metrics:
            {{ range $m := .disable_metrics }}
            {{ $m }}:
              enabled: false
            {{ end }}

      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin/vcenter:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/vcenter_logs.yaml
          parameters:
            listen_port: {{ .listen_port }}
            listen_ip: {{ .listen_ip }}
            {{ if .enable_tls_logs }}
            enable_tls: {{ .enable_tls_logs }}
            certificate_file: "{{ .logs_cert_file }}"
            key_file: "{{ .logs_key_file }}"
            {{ end }}
            parse_to: {{ .parse_to }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
