apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: aws_s3
  displayName: AWS S3
  icon: /icons/destinations/s3.svg
  description: Send logs, metrics, and traces to an AWS S3 Bucket.
spec:
  version: 0.0.1
  supportedPlatforms:
    - linux
    - windows
    - macos
    - kubernetes-daemonset
    - kubernetes-deployment
    - openshift-daemonset
    - openshift-deployment
  parameters:
    - name: telemetry_types
      label: Telemetry Types
      type: enums
      description: "Select which types of telemetry to export."
      validValues: ["Logs", "Metrics", "Traces"]
      default: ["Logs", "Metrics", "Traces"]
      options:
        gridColumns: 12

    - name: region
      label: Region
      description: The AWS recognized region string.
      type: enum
      default: us-east-1
      validValues:
        [
          us-east-1,
          us-east-2,
          us-west-1,
          us-west-2,
          af-south-1,
          ap-east-1,
          ap-southeast-3,
          ap-south-1,
          ap-northeast-3,
          ap-northeast-2,
          ap-southeast-1,
          ap-southeast-2,
          ap-northeast-1,
          ca-central-1,
          eu-central-1,
          eu-west-1,
          eu-west-2,
          eu-south-1,
          eu-west-3,
          eu-north-1,
          eu-central-2,
          me-south-1,
          me-central-1,
          sa-east-1,
          us-gov-east-1,
          us-gov-west-1,
        ]
      required: true

    - name: bucket
      label: Bucket
      description: Name of the S3 Bucket to export telemetry into.
      type: string
      required: true

    - name: prefix
      label: Folder Prefix
      description: Root directory of the bucket to export telemetry into.
      type: string
      default: ""

    - name: file_prefix
      label: File Prefix
      description: Prefix for the name of exported telemetry files.
      type: string
      default: ""

    - name: partition
      label: Granularity
      description: Granularity of the timestamps in the S3 key, either "minute" or "hour".
      type: enum
      validValues:
        - minute
        - hour
      default: minute
      advancedConfig: true

  logs:
    exporters: |
      {{ if has "Logs" .telemetry_types }}
      - awss3:
          s3uploader:
            region: {{ .region }}
            s3_bucket: {{ .bucket }}
            s3_prefix: {{ .prefix }}
            s3_partition: {{ .partition }}
      {{ end }}

  metrics:
    exporters: |
      {{ if has "Metrics" .telemetry_types }}
      - awss3:
          s3uploader:
            region: {{ .region }}
            s3_bucket: {{ .bucket }}
            s3_prefix: {{ .prefix }}
            s3_partition: {{ .partition }}
      {{ end }}

  traces:
    exporters: |
      {{ if has "Traces" .telemetry_types }}
      - awss3:
          s3uploader:
            region: {{ .region }}
            s3_bucket: {{ .bucket }}
            s3_prefix: {{ .prefix }}
            file_prefix: {{ .file_prefix }}
            s3_partition: {{ .partition }}
      {{ end }}
