apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: dynatrace
  displayName: Dynatrace
  icon: /icons/destinations/dynatrace.svg
  description: Send metrics to Dynatrace.
spec:
  parameters:
    # Base settings
    - name: metric_ingest_endpoint
      label: Metric Ingest Endpoint
      description: |
        Dynatrace Metrics Ingest v2 endpoint.

        Required if OneAgent is not running on the host.
      type: string
      default: ""
      options:
        gridColumns: 12
      documentation:
        - text: Read more
          url: https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/post-ingest-metrics

    - name: api_token
      label: Access Token
      description: Access Token that is restricted to 'Ingest metrics' scope. Required if Endpoint is specified
      type: string
      options:
        gridColumns: 12
        password: true
      documentation:
        - text: Read more
          url: https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication
      default: ""
      relevantIf:
        - name: metric_ingest_endpoint
          operator: notEquals
          value: ""

    - name: resource_to_telemetry_conversion
      label: Preserve Resource Attributes
      description: Whether to include resource attributes as metric dimensions in Dynatrace.
      type: bool
      default: true
      advancedConfig: true

    - name: prefix
      label: Metric Prefix
      description: Prefix to prepend to metrics
      type: string
      default: ""
      advancedConfig: true

    # TLS Settings
    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication, if mutual TLS is enabled.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    exporters: |
      - dynatrace:
          {{ if ne .metric_ingest_endpoint "" }}
          endpoint: {{ .metric_ingest_endpoint }}
          api_token: {{ .api_token }}
          {{ end }}
          {{ if .prefix }}
          prefix: {{ .prefix }}
          {{ end }}
          resource_to_telemetry_conversion:
            enabled: {{ .resource_to_telemetry_conversion }}
          tls:
            {{ if .enable_tls }}
            insecure: false
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            {{ else }}
            insecure: true
            {{ end }}
    # Must us a batch processor with max size of 1000 or else Dynatrace will throttle requests
    processors: |
      - batch:
          send_batch_max_size: 1000
          send_batch_size: 1000
          timeout: 30s
