apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: googlemanagedprometheus
  displayName: Google Managed Prometheus
  icon: /icons/destinations/prometheus.svg
  description: Send metrics to Google Managed Prometheus.
spec:
  version: 0.0.1
  parameters:
    - name: project
      label: Project ID
      description: The Google Cloud Project ID to send metrics to.
      type: string
      default: ""
      required: true

    - name: auth_type
      label: Authentication Method
      description: |
        The method used for authenticating to Google Cloud.
        auto: use the collectors environment when running on Google Cloud or the GOOGLE_APPLICATION_CREDENTIALS environment variable.
        json: contents of a Google Service Account credentials file.
        file: file path to a Google Service Account credential file.
      type: enum
      default: "auto"
      validValues:
        - "auto"
        - "json"
        - "file"
      required: true

    - name: credentials
      label: Credentials
      description: JSON value from a Google Service Account credential file.
      type: string
      default: ""
      options:
        gridColumns: 12
        multiline: true
      relevantIf:
        - name: auth_type
          operator: equals
          value: "json"
      required: true

    - name: credentials_file
      label: Credentials File
      description: Path to a Google Service Account credential file on the collector system. The collector's runtime user must have permission to read this file.
      type: string
      default: ""
      options:
        gridColumns: 12
      relevantIf:
        - name: auth_type
          operator: equals
          value: "file"
      required: true

    - name: default_location
      label: Default Location
      description: Google Managed Prometheus requires a "location" resource attribute. This parameter inserts the resource attribute if it does not already exist.
      type: enum
      default: us-central1
      validValues:
        - us-west1
        - us-west2
        - us-west3
        - us-west4
        - us-central1
        - us-east1
        - us-east4
        - northamerica-northeast1
        - southamerica-east1
        - europe-west2
        - europe-west1
        - europe-west4
        - europe-west6
        - europe-west3
        - europe-north1
        - asia-south1
        - asia-southeast1
        - asia-southeast2
        - asia-east2
        - asia-east1
        - asia-northeast1
        - asia-northeast2
        - asia-northeast3
        - australia-southeast1
        - aws:us-east-1
        - aws:us-east-2
        - aws:us-west-1
        - aws:us-west-2
        - aws:us-gov-east-1
        - aws:us-gov-west-1
        - aws:ca-central-1
        - aws:eu-west-1
        - aws:eu-west-2
        - aws:eu-west-3
        - aws:eu-south-1
        - aws:eu-south-2
        - aws:eu-north-1
        - aws:eu-central-1
        - aws:eu-central-2
        - aws:ap-east-1
        - aws:ap-south-2
        - aws:ap-southeast-3
        - aws:ap-southeast-4
        - aws:ap-south-1
        - aws:ap-northeast-3
        - aws:ap-northeast-2
        - aws:ap-southeast-1
        - aws:ap-southeast-2
        - aws:ap-northeast-1
        - aws:me-south-1
        - aws:me-central-1
        - aws:sa-east-1
        - aws:af-south-1
      documentation:
        - text: Read more
          url: https://cloud.google.com/monitoring/api/resources#tag_prometheus_target
      advancedConfig: true

  metrics:
    exporters: |
      - googlemanagedprometheus:
          project: "{{ .project }}"
          {{ if eq .auth_type "json" }}
          credentials: |-
            {{ .credentials | replace "\n" "" }}
          {{ else if eq .auth_type "file" }}
          credentials_file: "{{ .credentials_file }}"
          {{ end }}

    processors: |
      - resource:
          attributes:
            - key: "location"
              value: "{{ .default_location }}"
              action: insert

      - batch:
