apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: googlecloud
  displayName: Google Cloud
  icon: /icons/destinations/google-cloud-logging.svg
  description: Send metrics, traces, and logs to Google Cloud.
spec:
  parameters:
    - name: project
      label: Project ID
      description: The Google Cloud Project ID to send logs, metrics, and traces to.
      type: string
      default: ""
      required: true

    - name: auth_type
      label: Authentication Method
      description: |
        The method used for authenticating to Google Cloud.
        auto: use the collectors environment when running on Google Cloud or the GOOGLE_APPLICATION_CREDENTIALS environment variable.
        json: contents of a Google Service Account credentials file.
        file: file path to a Google Service Account credential file.
      type: enum
      default: "auto"
      validValues:
        - "auto"
        - "json"
        - "file"
      required: true

    - name: credentials
      label: Credentials
      description: JSON value from a Google Service Account credential file.
      type: string
      default: ""
      options:
        gridColumns: 12
        sensitive: true
      relevantIf:
        - name: auth_type
          operator: equals
          value: "json"
      required: true

    - name: credentials_file
      label: Credentials File
      description: Path to a Google Service Account credential file on the collector system. The collector's runtime user must have permission to read this file.
      type: string
      default: ""
      options:
        gridColumns: 12
      relevantIf:
        - name: auth_type
          operator: equals
          value: "file"
      required: true

    # Sending Queue Options
    - name: sending_queue_enabled
      label: Enable Sending Queue
      description: |
        Buffer telemetry data temporarily before sending to help ensure
        telemetry data is not lost in case of a temporary network outage.
      type: bool
      default: true
      documentation:
        - text: Read More
          url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      options:
        sectionHeader: true
      advancedConfig: true
      required: false

    - name: sending_queue_num_consumers
      label: Number of consumers
      description: Number of consumers that dequeue batches.
      type: int
      default: 10
      advancedConfig: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true

    - name: sending_queue_queue_size
      label: Queue size
      description: Maximum number of batches kept in memory before dropping.
      type: int
      default: 5000
      advancedConfig: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true

    - name: persistent_queue_enabled
      label: Enable Persistent Queuing
      description: |
        Buffer telemetry data to disk before sending to help ensure
        telemetry data is not lost in case of network outages or collector restarts.
      type: bool
      default: true
      advancedConfig: true
      documentation:
      - text: Read More
        url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      options:
        sectionHeader: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true

    - name: persistent_queue_directory
      label: Persistent Queue Directory
      description: The directory used to temporarily store telemetry data.
      type: string
      default: $OIQ_OTEL_COLLECTOR_HOME/storage
      advancedConfig: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true
        - name: persistent_queue_enabled
          operator: equals
          value: true

    - name: enable_compression
      label: Enable Compression
      description: Compress telemetry data using gzip before sending.
      type: bool
      default: true
      options:
        sectionHeader: true
        gridColumns: 12
      advancedConfig: true

    - name: enable_wal
      label: Metric Write-Ahead-Log
      description: Write metrics to a write-ahead-log before sending to help ensure metrics are not lost in case of network outages or collector restarts.
      type: bool
      default: false
      options:
        sectionHeader: true
        gridColumns: 12
      advancedConfig: true

    - name: wal_max_backoff
      label: WAL Max Retry Duration
      description: The maximum amount of time (minutes) to retry sending metrics from the write-ahead-log when a network error occurs.
      type: int
      default: 60
      advancedConfig: true
      required: false
      relevantIf:
        - name: enable_wal
          operator: equals
          value: true


  logs+metrics+traces:
    extensions: |
      {{ if and .persistent_queue_enabled .sending_queue_enabled }}
      - file_storage:
          directory: {{ .persistent_queue_directory }}
          compaction:
            on_rebound: true
            directory: {{ .persistent_queue_directory }}
      {{ end }}
    exporters: |
      - googlecloud:
          project: "{{ .project }}"
          {{ if eq .auth_type "json" }}
          credentials: |-
            {{ .credentials | replace "\n" "" }}
          {{ else if eq .auth_type "file" }}
          credentials_file: "{{ .credentials_file }}"
          {{ end }}
          log:
            resource_filters:
              - regex: .*
            {{ if .enable_compression }}
            compression: gzip
            {{ end }}
          {{ bpRenderOtelSendingQueueConfig .sending_queue_enabled .persistent_queue_enabled (bpComponentID "file_storage") .sending_queue_num_consumers .sending_queue_queue_size }}
          metric:
            {{ if .enable_compression }}
            compression: gzip
            {{ end }}
            {{ if .enable_wal }}
            experimental_wal_config:
              directory: $OIQ_OTEL_COLLECTOR_HOME/storage
              max_backoff: {{ .wal_max_backoff }}m
            {{ end }}
