apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: googlecloud
  displayName: Google Cloud
  icon: /icons/destinations/google-cloud-logging.svg
  description: Send metrics, traces, and logs to Google Cloud.
spec:
  parameters:
    - name: project
      label: Project ID
      description: The Google Cloud Project ID to send logs, metrics, and traces to.
      type: string
      default: ""
      required: true

    - name: auth_type
      label: Authentication Method
      description: |
        The method used for authenticating to Google Cloud.
        auto: use the collectors environment when running on Google Cloud or the GOOGLE_APPLICATION_CREDENTIALS environment variable.
        json: contents of a Google Service Account credentials file.
        file: file path to a Google Service Account credential file.
      type: enum
      default: "auto"
      validValues:
        - "auto"
        - "json"
        - "file"
      required: true

    - name: credentials
      label: Credentials
      description: JSON value from a Google Service Account credential file.
      type: string
      default: ""
      options:
        gridColumns: 12
        multiline: true
      relevantIf:
        - name: auth_type
          operator: equals
          value: "json"
      required: true

    - name: credentials_file
      label: Credentials File
      description: Path to a Google Service Account credential file on the collector system. The collector's runtime user must have permission to read this file.
      type: string
      default: ""
      options:
        gridColumns: 12
      relevantIf:
        - name: auth_type
          operator: equals
          value: "file"
      required: true

  logs+metrics+traces:
    exporters: |
      - googlecloud:
          project: "{{ .project }}"
          {{ if eq .auth_type "json" }}
          credentials: |-
            {{ .credentials | replace "\n" "" }}
          {{ else if eq .auth_type "file" }}
          credentials_file: "{{ .credentials_file }}"
          {{ end }}
          log:
            resource_filters:
              - regex: .*
