apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: grafana_cloud
  displayName: Grafana Cloud
  icon: /icons/destinations/grafana-cloud.svg
  description: Send metrics, traces, and logs to Grafana Cloud.
spec:
  parameters:
    - name: metric_instance_id
      label: Metric Instance ID
      type: string
      default: ""
      documentation:
        - text: Read more
          url: https://grafana.com/docs/grafana-cloud/data-configuration/otlp/send-data-otlp/
      required: true

    - name: api_key
      label: API Key
      description: Your Grafana.com API Key.  Should have at least MetricsPublisher role.
      type: string
      default: ""
      documentation:
        - text: Read more
          url: https://grafana.com/docs/grafana-cloud/data-configuration/otlp/send-data-otlp/
      required: true

    - name: gcp_zone
      label: Zone
      description: The GCP zone associated with your Grafana Cloud instance.
      type: enum
      default: prod-us-central-0
      required: true
      options:
          creatable: true
      validValues: 
          - prod-au-southeast-0
          - prod-eu-west-0
          - prod-sa-east-0
          - prod-ap-south-0
          - prod-ap-southeast-0
          - prod-gb-south-0
          - prod-us-central-0

  logs+metrics+traces:
    extensions: |
      - basicauth:
          client_auth:
            username: {{ .metric_instance_id }}
            password: {{ .api_key }}
    exporters: |
      - otlphttp:
          endpoint: https://otlp-gateway-{{ .gcp_zone}}.grafana.net/otlp
          auth:
            authenticator: {{ bpComponentID "basicauth" }}
    processors: |
      - batch:
