apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: grafana_cloud
  displayName: Grafana Cloud
  icon: /icons/destinations/grafana-cloud.svg
  description: Send metrics to Grafana Cloud.
spec:
  parameters:
    - name: metric_instance_id
      label: Metric Instance ID
      type: string
      default: ""
      documentation:
        - text: Read more
          url: https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/#sending-data-from-prometheus
      required: true

    - name: api_key
      label: API Key
      description: Your Grafana.com API Key.  Should have at least MetricsPublisher role.
      type: string
      default: ""
      documentation:
        - text: Read more
          url: https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/#sending-data-from-prometheus
      required: true

    - name: endpoint
      label: Endpoint
      description: The target URL to send metrics to (e.g. https://prometheus-us-central1.grafana.net/api/prom/push).
      type: string
      default: ""
      documentation:
        - text: Read more
          url: https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/#sending-data-from-prometheus
      required: true

    # Advanced Options
    - name: namespace
      label: Namespace
      description: When set, exports metrics under the provided value.
      type: string
      advancedConfig: true
      required: false
      default: ""

    - name: external_labels
      label: External Labels
      description: Label names and values to be attached as metric attributes.
      type: map
      default: {}
      advancedConfig: true
      options:
        gridColumns: 12

  metrics:
    exporters: |
      - prometheusremotewrite:
          endpoint: "{{ .endpoint }}"
          headers:
            Authorization: "Basic {{ printf "%s:%s" .metric_instance_id .api_key | b64enc }}"
                    
          {{ if ne .namespace "" }}
          namespace: {{ .namespace }}
          {{ end }}

          {{ $length := len .external_labels }} {{ if ne $length 0 }}
          external_labels:
            {{ range $k, $v := .external_labels }}
            {{ $k }}: {{ $v }}
            {{ end }}
          {{ end }}

          resource_to_telemetry_conversion:
            enabled: true
    processors: |
      - batch:
