apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: otlp_grpc
  displayName: OpenTelemetry (OTLP)
  icon: /icons/destinations/otlp.svg
  description: Send metrics, logs, and traces to an OTLP endpoint.
spec:
  parameters:
    - name: hostname
      label: Hostname
      description: Hostname or IP address where the exporter will send OTLP data.
      type: string
      default: ""
      required: true

    - name: grpc_port
      label: Port
      description: TCP port to which the exporter is going to send OTLP data.
      type: int
      default: 4317
      relevantIf:
        - name: protocol
          operator: equals
          value: "grpc"

    - name: http_port
      label: Port
      description: TCP port to which the exporter is going to send OTLP data.
      type: int
      default: 4318
      relevantIf:
        - name: protocol
          operator: equals
          value: "http"

    - name: protocol
      label: Protocol
      description: The OTLP protocol to use when sending OTLP telemetry.
      type: enum
      default: grpc
      validValues:
        - grpc
        - http

    # TLS
    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip verification of the server's certificate.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Optional Certificate authority file used to validate the server's certificate.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: mutual_tls
      label: Mutual TLS
      description: Whether or not to use client TLS authentication (mTLS).
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Client Certificate File
      description: A path to the client certificate to be used for mutual TLS.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Client Private Key
      description: A path to the client private key to be used for mutual TLS.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

  logs+metrics+traces:
    exporters: |
      {{ if eq .protocol "grpc" }}
      - otlp:
          endpoint: {{ .hostname }}:{{ .grpc_port }}
          tls:
            {{ if .enable_tls }}
            insecure: false
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            {{ if .mutual_tls }}
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            {{ end }}
            {{ else }}
            insecure: true
            {{ end }}
      {{ end }}

      {{ if eq .protocol "http" }}
      - otlphttp:
          {{ if .enable_tls }}
          endpoint: https://{{ .hostname }}:{{ .http_port }}
          {{ else }}
          endpoint: http://{{ .hostname }}:{{ .http_port }}
          {{ end }}
          {{ if .enable_tls }}
          tls:
            insecure_skip_verify: {{ .insecure_skip_verify }}
            ca_file: "{{ .ca_file }}"
            {{ if .mutual_tls }}
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            {{ end }}
          {{ end }}
      {{ end }}

    processors: |
      - batch:
