apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: prometheus_remote_write
  displayName: Prometheus Remote Write
  icon: /icons/destinations/prometheus.svg
  description: Sends OpenTelemetry metrics to Prometheus remote write compatible backends.
spec:
  parameters:
    - name: hostname
      label: Hostname
      description: The hostname or IP address for the remote write backend.
      required: true
      type: string
      default: ""

    - name: port
      label: Port
      description: The port remote write backend.
      required: true
      type: int
      default: 9009

    - name: path
      label: API Path
      description: "The API Path of the remote write URL. Ex: api/v1/metrics"
      type: string
      required: true
      default: ""

    - name: namespace
      label: Namespace
      description: Prefix to attach to each metric name.
      type: string
      default: ""
      advancedConfig: true

    - name: enable_resource_to_telemetry_conversion
      label: Convert Resource Attributes to Metric Attributes
      description: When enabled will convert all resource attributes to metric attributes.
      type: bool
      default: false
      advancedConfig: true

    # Advanced Options
    - name: headers
      label: Additional HTTP Headers
      description: |
        Additional headers to attach to each HTTP Request.

        The following headers cannot be changed: Content-Encoding, Content-Type, X-Prometheus-Remote-Write-Version, User-Agent
      type: map
      default: {}
      advancedConfig: true
      options:
        gridColumns: 12

    - name: external_labels
      label: External Labels
      description: Label names and values to be attached as metric attributes.
      type: map
      default: {}
      advancedConfig: true
      options:
        gridColumns: 12

    # TLS Settings
    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: strict_tls_verify
      label: Strict TLS Certificate Verification
      description: Enable to require TLS certificate verification.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates. Not required if the collector's operating system already trusts the certificate authority.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: strict_tls_verify
          operator: equals
          value: true
      advancedConfig: true

    - name: mutual_tls
      label: Mutual TLS Authentication
      description: Enable to require TLS mutual authentication.
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: strict_tls_verify
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: Mutual TLS Client Certificate File
      description: A TLS certificate used for client authentication, if mutual TLS is enabled.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: Mutual TLS Client Private Key File
      description: A TLS private key used for client authentication, if mutual TLS is enabled.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

    # WAL Settings
    - name: enable_write_ahead_log
      label: Write Ahead Log
      description: Whether or not to enable a Write Ahead Log for the exporter.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: wal_storage_path
      label: Storage Directory
      description: Name to use for the directory the WAL is stored in. Must be unique to this destination.
      type: string
      default: prometheus_rw
      required: true
      advancedConfig: true
      relevantIf:
        - name: enable_write_ahead_log
          operator: equals
          value: true

    - name: wal_buffer_size
      label: Buffer Size
      description: Number of objects to store in Write Ahead Log before truncating.
      type: int
      default: 300
      advancedConfig: true
      relevantIf:
        - name: enable_write_ahead_log
          operator: equals
          value: true

    - name: wal_truncate_frequency
      label: Truncate Frequency
      description: How often, in seconds, the Write Ahead Log should be truncated.
      type: int
      default: 60
      advancedConfig: true
      relevantIf:
        - name: enable_write_ahead_log
          operator: equals
          value: true

    # Retry on failure
    - name: retry_on_failure_enabled
      label: Enable Retry on Failure
      description: Attempt to resend telemetry data that has failed to be transmitted to the destination.
      type: bool
      documentation:
        - text: Read More
          url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      default: true
      options:
        sectionHeader: true
      advancedConfig: true
      required: false

    - name: retry_on_failure_initial_interval
      label: Initial interval
      description: Time (in seconds) to wait after the first failure before retrying.
      type: int
      default: 5
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    - name: retry_on_failure_max_interval
      label: Max interval
      description: The upper bound (in seconds) on backoff.
      type: int
      default: 30
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    - name: retry_on_failure_max_elapsed_time
      label: Max elapsed time
      description: The maximum amount of time (in seconds) spent trying to send a batch, used to avoid a never-ending retry loop.
      type: int
      default: 300
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

  metrics:
    exporters: |
      - prometheusremotewrite:
          {{ if .enable_tls }}
          endpoint: https://{{ .hostname }}:{{ .port }}/{{ .path }}
          {{ else }}
          endpoint: http://{{ .hostname }}:{{ .port }}/{{ .path }}
          {{ end }}

          {{ $length := len .headers }} {{ if ne $length 0 }}
          headers:
            {{ range $k, $v := .headers }}
            {{ $k }}: {{ $v }}
            {{ end }}
          {{ end }}

          {{ $length := len .external_labels }} {{ if ne $length 0 }}
          external_labels:
            {{ range $k, $v := .external_labels }}
            {{ $k }}: {{ $v }}
            {{ end }}
          {{ end }}

          {{ if ne .namespace "" }}
          namespace: {{ .namespace }}
          {{ end }}

          {{ if .enable_write_ahead_log }}
          wal:
            directory: $OIQ_OTEL_COLLECTOR_HOME/storage/{{ .wal_storage_path }}
            buffer_size: {{ .wal_buffer_size }}
            truncate_frequency: {{ .wal_truncate_frequency}}s
          {{ end }}

          resource_to_telemetry_conversion:
            enabled: {{ .enable_resource_to_telemetry_conversion }}
          {{ if .enable_tls }}
          tls:
            {{ if .strict_tls_verify }}
            insecure_skip_verify: false
            {{ if .ca_file }}
            ca_file: {{ .ca_file }}
            {{ end }}
            {{ else }}
            insecure_skip_verify: true
            {{ end }}
            {{ if .mutual_tls }}
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            {{ end }}
          {{ end }}
          {{ bpRenderOtelRetryOnFailureConfig .retry_on_failure_enabled .retry_on_failure_initial_interval .retry_on_failure_max_interval .retry_on_failure_max_elapsed_time }} 
