apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: prometheus
  displayName: Prometheus
  icon: /icons/destinations/prometheus.svg
  description: Serve Prometheus compatible metrics, scrapable by a Prometheus server.
spec:
  parameters:
    - name: listen_address
      label: Listen Address
      description: >
        The IP address the Prometheus exporter should 
        listen on, to be scraped by a Prometheus server.
      type: string
      default: "127.0.0.1"

    - name: listen_port
      label: Listen Port
      description: >
        The TCP port the Prometheus exporter should listen on,
        to be scraped by a Prometheus server.
      type: int
      default: 9000

    - name: namespace
      label: Namespace
      description: When set, exports metrics under the provided value.
      type: string
      advancedConfig: true
      required: false
      default: ""

    # TLS
    - name: configure_tls
      label: Configure TLS
      description: Configure advanced TLS settings.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: cert_file
      label: TLS Server Certificate File
      description: The TLS certificate.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: configure_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: TLS Server Private Key File
      description: The TLS private key.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: configure_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates. Optional for TLS.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: configure_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: mutual_tls
      label: Mutual TLS
      description: Whether or not to use mutual TLS authentication.
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: configure_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: client_ca_file
      label: TLS Certificate Authority File for mTLS
      description: Certificate authority used to validate client TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: configure_tls
          operator: equals
          value: true
        - name: mutual_tls
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    exporters: |
      - prometheus:
          endpoint: "{{ .listen_address }}:{{ .listen_port }}"
          resource_to_telemetry_conversion:
            enabled: true
          namespace: {{ .namespace }}
          {{ if .configure_tls }}
          tls:
            cert_file: "{{ .cert_file }}"
            key_file: "{{ .key_file }}"
            ca_file: "{{ .ca_file }}"
            {{ if .mutual_tls }}
            client_ca_file: "{{ .client_ca_file }}"
            {{ end }}
          {{ end }}
    processors: |
      - batch:
