apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: splunkhec
  displayName: Splunk HTTP Event Collector (HEC)
  icon: /icons/destinations/splunk.svg
  description: Send logs to a Splunk HTTP Event Collector.
spec:
  parameters:
    - name: token
      label: Token
      description: Authentication token used when connecting to the HTTP Event Collector.
      documentation:
        - text: Read more
          url: https://docs.splunk.com/Documentation/Splunk/latest/Data/UsetheHTTPEventCollector.
      type: string
      default: ""
      required: true
    
    - name: index
      label: Index
      description: Optional name of the Splunk index targeted.
      type: string
      default: ""

    - name: hostname
      label: Hostname
      description: Hostname or IP address of the HTTP Event Collector.
      type: string
      default: "localhost"

    - name: port
      label: Port
      description: TCP port to which the exporter is going to send data.
      type: int
      default: 8088

    - name: path
      label: Path
      description: The HTTP API path to which the exporter is going to send data.
      type: string
      default: "/services/collector/event"
      advancedConfig: true
      options:
        gridColumns: 12

    # Sizing Options
    - name: max_request_size
      label: Max Request Size
      description: The maximum size (in bytes) of a request sent to the destination. A value of 0 will send unbounded requests. The maximum allowed value is 838860800 (~800MB).
      type: int
      default: 2097152
      advancedConfig: true

    - name: max_event_size
      label: Max Event Size
      description: The maximum size (in bytes) of an individual event. Events larger than this will be dropped. The maximum allowed value is 838860800 (~800MB).
      type: int
      default: 2097152
      advancedConfig: true

    - name: enable_compression
      label: Enable Compression
      description: Compress telemetry data using gzip before sending.
      type: bool
      default: true
      options:
        sectionHeader: true
        gridColumns: 12
      advancedConfig: true

    # TLS Options
    - name: enable_tls
      label: Enable TLS
      description: Whether or not to use TLS.
      type: bool
      default: false
      options:
        sectionHeader: true
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    # Retry on failure
    - name: retry_on_failure_enabled
      label: Enable Retry on Failure
      description: Attempt to resend telemetry data that has failed to be transmitted to the destination.
      type: bool
      documentation:
        - text: Read More
          url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      default: true
      options:
        sectionHeader: true
      advancedConfig: true
      required: false

    - name: retry_on_failure_initial_interval
      label: Initial interval
      description: Time (in seconds) to wait after the first failure before retrying.
      type: int
      default: 5
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    - name: retry_on_failure_max_interval
      label: Max interval
      description: The upper bound (in seconds) on backoff.
      type: int
      default: 30
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    - name: retry_on_failure_max_elapsed_time
      label: Max elapsed time
      description: The maximum amount of time (in seconds) spent trying to send a batch, used to avoid a never-ending retry loop.
      type: int
      default: 300
      advancedConfig: true
      required: false
      relevantIf:
        - name: retry_on_failure_enabled
          operator: equals
          value: true

    # Sending Queue Options
    - name: sending_queue_enabled
      label: Enable Sending Queue
      description: |
        Buffer telemetry data temporarily before sending to help ensure
        telemetry data is not lost in case of a temporary network outage.
      type: bool
      default: true
      documentation:
        - text: Read More
          url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      options:
        sectionHeader: true
      advancedConfig: true
      required: false

    - name: sending_queue_num_consumers
      label: Number of consumers
      description: Number of consumers that dequeue batches.
      type: int
      default: 10
      advancedConfig: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true

    - name: sending_queue_queue_size
      label: Queue size
      description: Maximum number of batches kept in memory before dropping.
      type: int
      default: 5000
      advancedConfig: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true

    - name: persistent_queue_enabled
      label: Enable Persistent Queuing
      description: |
        Buffer telemetry data to disk before sending to help ensure
        telemetry data is not lost in case of network outages or collector restarts.
      type: bool
      default: true
      advancedConfig: true
      documentation:
      - text: Read More
        url: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md
      options:
        sectionHeader: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true
    
    - name: persistent_queue_directory
      label: Persistent Queue Directory
      description: The directory used to temporarily store telemetry data.
      type: string
      default: $OIQ_OTEL_COLLECTOR_HOME/storage
      advancedConfig: true
      required: false
      relevantIf:
        - name: sending_queue_enabled
          operator: equals
          value: true
        - name: persistent_queue_enabled
          operator: equals
          value: true

  logs:
    extensions: |
      {{ if and .persistent_queue_enabled .sending_queue_enabled }}
      - file_storage:
          directory: {{ .persistent_queue_directory }}
          compaction:
            on_rebound: true
            directory: {{ .persistent_queue_directory }}
      {{ end }}
    exporters: |
      - splunk_hec:
          token: "{{ .token }}"
          {{ if .index }}
          index: "{{ .index }}"
          {{ end }}
          max_content_length_logs: {{ .max_request_size | int64 }}
          max_content_length_metrics: {{ .max_request_size | int64 }}
          max_content_length_traces: {{ .max_request_size | int64 }}
          max_event_size: {{ .max_event_size | int64 }}
          disable_compression: {{ not .enable_compression }}
          {{ if .enable_tls }}
          endpoint: "https://{{ .hostname }}:{{ .port }}{{ .path }}"
          tls:
            insecure: false
            insecure_skip_verify: {{ .insecure_skip_verify }}
            {{ if .ca_file }}
            ca_file: "{{ .ca_file }}"
            {{ end }}
          {{ else }}
          endpoint: "http://{{ .hostname }}:{{ .port }}{{ .path }}"
          tls:
            insecure: true
          {{ end }}
          {{ bpRenderOtelRetryOnFailureConfig .retry_on_failure_enabled .retry_on_failure_initial_interval .retry_on_failure_max_interval .retry_on_failure_max_elapsed_time }} 
          {{ bpRenderOtelSendingQueueConfig .sending_queue_enabled .persistent_queue_enabled (bpComponentID "file_storage") .sending_queue_num_consumers .sending_queue_queue_size }}
    processors: |
      - batch:
