apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
  name: macos
  labels:
    platform: macos
    app: cabin
spec:
  contentType: text/yaml
  sources:
  # name is optional and this will become MacOS_1 if none is specified or MacOS_name if a name is specified
  - type: MacOS
    id: MacOS_1
    parameters:
      # using default parameter values for anything missing
      - name: enable_system_log
        value: false
  - type: MacOS
    id: MacOS_2
    parameters:
      # using default parameter values for anything missing
      - name: enable_system_log
        value: true
  destinations:
  # name indicates an existing resource with the specified name, destinations could also be inline without a name
  - name: cabin-production-logs
    id: cabin-production-logs
  selector:
    matchLabels:
      "configuration": macos
