
apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: MacOS
  displayName: Mac OS
  icon: /icons/sources/macos.svg
  description: Log parser for MacOS
spec:
  # settings below take directly from stanza-plugins
  version: 0.0.2
  supportedPlatforms:
    - macos
  parameters:
    - name: enable_system_log
      label: System Logs
      description: Enable to collect MacOS system logs
      type: bool
      default: true
    - name: system_log_path
      label: System Log Path
      description: The absolute path to the System log
      type: string
      default: "/var/log/system.log"
      relevantIf:
        - name: enable_system_log
          operator: equals
          value: true
    - name: enable_install_log
      label: Install Logs
      description: Enable to collect MacOS install logs
      type: bool
      default: true
    - name: install_log_path
      label: Install Log Path
      description: The absolute path to the Install log
      type: string
      default: "/var/log/install.log"
      relevantIf:
        - name: enable_install_log
          operator: equals
          value: true
    - name: collection_interval_seconds
      label: Collection Interval
      type: int
      default: "30"
    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
    - name: enable_tls
      label: Enable TLS
      description: Enable TLS when connecting to Aerospike.
      type: bool
      required: true
      default: false
      advancedConfig: true

    - name: insecure_skip_verify
      label: Skip TLS Certificate Verification
      description: Enable to skip TLS certificate verification.
      type: bool
      default: false
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: server_name
      label: TLS Server Name
      description: ServerName requested by client for virtual hosting.
      type: string
      required: true
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: ca_file
      label: TLS Certificate Authority File
      description: Certificate authority used to validate TLS certificates.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: cert_file
      label: TLS Client Certificate File
      description: A TLS certificate used for client authentication.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

    - name: key_file
      label: TLS Client Private Key File
      description: A TLS private key used for client authentication.
      type: string
      required: false
      default: ""
      relevantIf:
        - name: enable_tls
          operator: equals
          value: true
      advancedConfig: true

  metrics:
    # receivers, processors, exporters, and extensions can all be specified
    receivers: |
      - hostmetrics:
          collection_interval: 1m
          scrapers:
            load:
  logs:
    receivers: |
      - plugin/macos:
          plugin:
            name: macos
          parameters:
          - name: enable_system_log
            value: {{ .enable_system_log }}
          - name: system_log_path
            value: {{ .system_log_path }}
          - name: enable_install_log
            value: {{ .enable_install_log }}
          - name: install_log_path
            value: {{ .install_log_path }}
          - name: start_at
            value: {{ .start_at }}
          - name: collection_interval_seconds
            value: {{ .collection_interval_seconds }}s
      - plugin/journald:
          plugin:
            name: journald
