apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: add_attribute
  displayName: Add Attribute
  description: Insert, update, or upsert telemetry attributes.
  labels:
    category: Transform
spec:
  version: 0.0.2
  parameters:
    - name: telemetry_types
      label: Enable Telemetry
      type: enums
      description: "Select which types of telemetry you'd like to enable this processor for."
      validValues: ["Metrics", "Logs", "Traces"]
      default: ["Metrics", "Logs", "Traces"]
      options:
        gridColumns: 12


    - name: action
      label: Action
      type: enum
      description: "insert: Add attribute if it does not exist. update: Update existing value. upsert: Insert or update."
      default: upsert
      validValues:
        - insert
        - update
        - upsert

    - name: attributes
      label: Attributes
      type: map
      required: true
      options:
        gridColumns: 12

  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
        - attributes:
            actions:
              {{ range $k, $v := .attributes }}
              - key: '{{ $k }}'
                value: {{ $v }}
                action: {{ $.action }}
              {{ end }}
      {{ end }}
  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
        - attributes:
            actions:
              {{ range $k, $v := .attributes }}
              - key: '{{ $k }}'
                value: {{ $v }}
                action: {{ $.action }}
              {{ end }}
      {{ end }}
  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
        - attributes:
            actions:
              {{ range $k, $v := .attributes }}
              - key: '{{ $k }}'
                value: {{ $v }}
                action: {{ $.action }}
              {{ end }}
      {{ end }}
