apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: custom
  displayName: Custom
  description: Insert a custom OpenTelemetry processor configuration.
  labels:
    category: Advanced

spec:
  version: 0.0.1
  parameters:
    - name: telemetry_types
      label: Telemetry Types
      type: enums
      description: "Select which types of telemetry the processor supports."
      validValues: ["Metrics", "Logs", "Traces"]
      default: []

    - name: configuration
      label: Configuration
      description: Enter any supported Processor and the YAML will be inserted into the configuration.
      type: yaml
      options:
        gridColumns: 12
      required: true
      documentation:
        - text: Processor Syntax
          url: https://github.com/observIQ/bindplane-agent/blob/main/docs/processors.md

  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}

  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}


  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}
