apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: filter_metric_name
  displayName: Filter by Metric Name
  description: Filter by metric name.
  labels:
    category: Filter-And-Reduce
spec:
  version: 0.0.2
  parameters:
    - name: action
      label: Action
      description: When set to include, anything that does not match is filtered.
      type: enum
      validValues:
        - include
        - exclude
      default: exclude

    - name: match_type
      label: Match Type
      description: Strict matching requires that the metric name be an exact match. Regexp matching uses 're2' to match a metric name.
      type: enum
      validValues:
        - strict
        - regexp
      default: strict

    - name: metric_names
      label: Metrics
      description: List of metric names to match against. All matches are filtered.
      type: strings
      options:
        gridColumns: 12
      required: true

  metrics:
    processors: |
      - filter:
          metrics:
            {{ .action }}:
              match_type: {{ .match_type }}
              metric_names:
                {{ range $name := .metric_names }}
                - {{ $name | quote }}
                {{ end }}
