apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: filter_field
  displayName: Filter by Fields
  description: Filter telemetry based on field values.
  labels:
    category: Filter-And-Reduce
spec:
  version: 0.0.3
  parameters:
    - name: telemetry_types
      label: Enable Telemetry
      type: enums
      description: "The telemetry types to enable this processor for."
      validValues: ["Metrics", "Logs", "Traces"]
      default: []
      options:
        gridColumns: 12

    - name: action
      label: Action
      description: "The action to take when the filter condition is met. Include will retain matching telemetry. Exclude will remove matching telemetry."
      type: enum
      validValues:
        - include
        - exclude
      default: exclude
      relevantIf:
        - name: telemetry_types
          operator: containsAny
          value: ["Logs", "Metrics", "Traces"]

    - name: match_type
      label: Match Type
      description: "The method for matching values. Strict requires an exact match. Regexp uses an expression to match against."
      documentation:
        - text: Regexp Syntax
          url: https://github.com/google/re2/wiki/Syntax
      type: enum
      validValues:
        - strict
        - regexp
      default: strict
      relevantIf:
        - name: telemetry_types
          operator: containsAny
          value: ["Logs", "Metrics", "Traces"]

    - name: resources
      label: Resource Fields
      description: "A list of resource fields to match."
      type: map
      default: {}
      options:
        gridColumns: 12
        labels:
          key: Field
          value: Value
      relevantIf:
        - name: telemetry_types
          operator: containsAny
          value: ["Logs", "Metrics", "Traces"]

    - name: attributes
      label: Attribute Fields
      description: "A list of attribute fields to match."
      type: map
      default: {}
      options:
        gridColumns: 12
        labels:
          key: Field
          value: Value
      relevantIf:
        - name: telemetry_types
          operator: containsAny
          value: ["Logs", "Metrics", "Traces"]

    - name: bodies
      label: Body Fields
      description: "A list of body fields to match."
      type: map
      default: {}
      options:
        gridColumns: 12
        labels:
          key: Field
          value: Value
      relevantIf:
        - name: telemetry_types
          operator: containsAny
          value: ["Logs"]

  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
      {{ if or .resources .attributes }}
      - filter/metrics:
          error_mode: ignore
          metrics:
            datapoint:
            - {{ if eq .action "include" }} not{{ end }} (
              {{- $firstAttr := true -}}
              {{ range $k, $v := .attributes }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              attributes[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(attributes[{{ $k | quote }}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              {{- range $k, $v := .resources }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              resource.attributes[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(resource.attributes[{{ $k | quote}}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              )
      {{ end }}
      {{ end }}

  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
      {{ if or .resources .attributes .bodies }}
      - filter/logs:
          error_mode: ignore
          logs:
            log_record:
            - {{ if eq .action "include" }} not{{ end }} (
              {{- $firstAttr := true -}}
              {{ range $k, $v := .attributes }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              attributes[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(attributes[{{ $k | quote }}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              {{- range $k, $v := .resources }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              resource.attributes[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(resource.attributes[{{ $k | quote}}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              {{- range $k, $v := .bodies }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              body[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(body[{{ $k | quote}}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              )
      {{ end }}
      {{ end }}

  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
      {{ if or .resources .attributes }}
      - filter/traces:
          error_mode: ignore
          traces:
            span:
            - {{ if eq .action "include" }} not{{ end }} (
              {{- $firstAttr := true -}}
              {{ range $k, $v := .attributes }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              attributes[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(attributes[{{ $k | quote }}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              {{- range $k, $v := .resources }}
              {{ if not $firstAttr }} and{{ end }}
              {{- if eq $.match_type "strict" }}
              resource.attributes[{{ $k | quote }}] == {{ $v | quote }}
              {{ else }}
              IsMatch(resource.attributes[{{ $k | quote}}], {{ $v | quote }})
              {{ end }}
              {{- $firstAttr = false -}}
              {{ end }}
              )
      {{ end }}
      {{ end }}
