apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: group_by_attributes
  displayName: Group by Attributes
  description: Group telemetry into the same resources based on matching attributes.
  labels:
    category: Advanced

spec:
  version: 0.0.2
  parameters:
    - name: enable_logs
      label: Enable Logs
      type: bool
      default: true
      required: false

    - name: log_attributes
      label: Attribute Fields
      description: "A list of log attribute field names to group by. If none are specified, resources with the same attributes will be compacted."
      type: strings
      default: []
      required: false
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: enable_metrics
      label: Enable Metrics
      type: bool
      default: true
      required: false

    - name: metric_attributes
      label: Attribute Fields
      description: "A list of metric datapoint attribute field names to group by. If none are specified, resources with the same attributes will be compacted."
      type: strings
      default: []
      required: false
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: enable_traces
      label: Enable Traces
      type: bool
      default: true
      required: false

    - name: trace_attributes
      label: Attribute Fields
      description: "A list of span attribute field names to group by. If none are specified, resources with the same attributes will be compacted."
      type: strings
      default: []
      required: false
      relevantIf:
        - name: enable_traces
          operator: equals
          value: true

  logs:
    processors: |
      {{ if .enable_logs }}
      - groupbyattrs:
          {{ if .log_attributes }}
          keys:
            {{ range $k := .log_attributes }}
            - {{ $k | quote }}
            {{ end }}
          {{ end }}
      {{ end }}

  metrics:
    processors: |
      {{ if .enable_metrics }}
      - groupbyattrs:
          {{ if .metric_attributes }}
          keys:
            {{ range $k := .metric_attributes }}
            - {{ $k | quote }}
            {{ end }}
          {{ end }}
      {{ end }}

  traces:
    processors: |
      {{ if .enable_traces }}
      - groupbyattrs:
          {{ if .trace_attributes }}
          keys:
            {{ range $k := .trace_attributes }}
            - {{ $k | quote }}
            {{ end }}
          {{ end }}
      {{ end }}
