apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: log_dedup
  displayName: Deduplicate Logs 
  description: Aggregates logs over a specified time period and removes duplicates.
spec:
  version: 0.0.1
  parameters:
    - name: interval
      label: Interval
      description: The time interval (in seconds) over which to deduplicate logs.
      type: int
      default: 10
      required: true

    - name: log_count_attribute
      label: Count Attribute Name
      description: The name of the attribute to store the count of logs deduplicated.
      type: string
      required: true
      default: log_count

    - name: exclude_fields
      label: Excluded Fields
      description: Fields to exclude from the deduplication matching. Must start with 'body' or 'attributes'.
      options:
        gridColumns: 12
      type: strings
      default: []

    - name: timezone
      label: Timezone
      advancedConfig: true
      description: Timezone is used to localize the observed timestamp attributes.
      type: string
      required: true
      default: UTC

  logs:
    processors: |
      - logdedup:
          interval: {{ .interval }}s
          timezone: {{ .timezone | quote }}
          log_count_attribute: {{ .log_count_attribute | quote }}
          {{ if .exclude_fields }}
          exclude_fields:
            {{ range $ef := .exclude_fields }}
            - '{{ $ef }}'
            {{ end }}
          {{ end }}
