apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: mask_sensitive_data
  displayName: Mask Sensitive Data
  description: Detect and mask sensitive data in collected telemetry.
spec:
  version: 0.0.1
  parameters:
    - name: telemetry_types
      label: Telemetry Types
      type: enums
      description: "Select which types of telemetry to apply masking rules to."
      validValues: ["Metrics", "Logs", "Traces"]
      default: []

    - name: rules
      label: Rules
      required: true
      description: Regex expression to find matching logs.
      type: map
      documentation:
        - text: How to Mask Attributes
          url: https://github.com/observIQ/observiq-otel-collector/tree/main/processor/maskprocessor#how-it-works
      options:
        gridColumns: 12
      default:
        email: \b[a-zA-Z0-9._\/\+\-—|]+@[A-Za-z0-9.\-—|]+\.?[a-zA-Z|]{0,6}\b
        ssn: \b\d{3}[- ]\d{2}[- ]\d{4}\b
        credit_card: \b(?:(?:(?:\d{4}[- ]?){3}\d{4}|\d{15,16}))\b
        phone: \b((\+|\b)[1l][\-\. ])?\(?\b[\dOlZSB]{3,5}([\-\. ]|\) ?)[\dOlZSB]{3}[\-\. ][\dOlZSB]{4}\b

    - name: exclude
      label: Exclude
      description: A list of json dot notation fields that will be excluded from masking. The prefixes resource, attributes, and body can be used to indicate the root of the field.
      type: strings
      default: []

  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
      - mask:
          rules:
            {{ range $k, $v := .rules }}
              {{ $k }}: {{ $v }}
            {{ end }}

          {{ if .exclude }}
          exclude: {{ .exclude }}
          {{ end }}
      {{ end }}

  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
      - mask:
          rules:
            {{ range $k, $v := .rules }}
              {{ $k }}: {{ $v }}
            {{ end }}

          {{ if .exclude }}
          exclude: {{ .exclude }}
          {{ end }}
      {{ end }}

  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
      - mask:
          rules:
            {{ range $k, $v := .rules }}
              {{ $k }}: {{ $v }}
            {{ end }}

          {{ if .exclude }}
          exclude: {{ .exclude }}
          {{ end }}
      {{ end }}
