apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: metric_stats
  displayName: Metric Statistics
  description: Compute statistics for incoming metrics over a fixed time interval.
spec:
  version: 0.0.1
  parameters:
    - name: interval
      label: Interval
      description: The time interval (in seconds) over which to calculate metric statistics.
      type: int
      default: 60
      required: true

    - name: include
      label: Include
      description: A regex that must match against the metric's name in order to calculate statistics from it.
      type: string
      default: ".*"
      required: true
      
    - name: stats
      label: Statistics
      description: Select which statistics to calculate on matching metrics.
      type: enums
      validValues: ["min", "max", "avg", "first", "last"]
      default: ["min", "max", "avg"]

  metrics:
    processors: |
      - metricstats:
          interval: {{ .interval }}s
          include: {{ .include | replace "$" "$$" | quote }}
          stats:
          {{ range $s := .stats }}
            - {{ $s }}
          {{end}}
