apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: rename_field
  displayName: Rename Fields
  description: Rename resource, attribute, or body fields.
  labels:
    category: Transform
spec:
  version: 1.0.1
  parameters:
    # Logs
    - name: enable_logs
      label: Enable Logs
      type: bool
      default: false

    - name: log_condition
      label: Condition
      description: "An OTTL condition that must evaluate to true to apply this processor. By default, the processor applies to all logs."
      type: string
      default: "true"
      required: true
      options:
        gridColumns: 12
      documentation:
        - text: OTTL Log Context
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/ottllog/README.md
        - text: OTTL Booleans
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md#booleans
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: log_resource_keys
      label: Resource Fields
      description: "A list of resource fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: log_attribute_keys
      label: Attribute Fields
      description: "A list of attribute fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: log_body_keys
      label: Body Fields
      description: "A list of body fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      type: bool
      default: false

    - name: datapoint_condition
      label: Condition
      description: "An OTTL condition that must evaluate to true to apply this processor. By default, the processor applies to all datapoints."
      type: string
      default: "true"
      required: true
      options:
        gridColumns: 12
      documentation:
        - text: OTTL Datapoint Context
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/ottldatapoint/README.md
        - text: OTTL Booleans
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md#booleans
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: metric_resource_keys
      label: Resource Fields
      description: "A list of resource fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: metric_attribute_keys
      label: Attribute Fields
      description: "A list of attribute fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    # Trace
    - name: enable_traces
      label: Enable Traces
      type: bool
      default: false

    - name: span_condition
      label: Condition
      description: "An OTTL boolean expression that must evaluate to true to apply this processor. By default, the processor applies to all spans."
      type: string
      default: "true"
      required: true
      options:
        gridColumns: 12
      documentation:
        - text: OTTL Span Context
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan
        - text: OTTL Booleans
          url: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md#booleans
      relevantIf:
        - name: enable_traces
          operator: equals
          value: true

    - name: trace_resource_keys
      label: Resource Fields
      description: "A list of resource fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_traces
          operator: equals
          value: true

    - name: trace_attribute_keys
      label: Attribute Fields
      description: "A list of attribute fields to rename."
      type: map
      default: {}
      required: false
      options:
        gridColumns: 12
        labels:
          key: Old Name
          value: New Name
      relevantIf:
        - name: enable_traces
          operator: equals
          value: true

  metrics:
    processors: |
      {{ if .enable_metrics }}
      {{ if or .metric_resource_keys .metric_attribute_keys }}
      - transform/metrics:
          error_mode: ignore
          metric_statements:
            {{ if .metric_resource_keys }}
            - context: datapoint
              statements:
              {{ range $k, $v := .metric_resource_keys }}
              - replace_all_patterns(resource.attributes, "key", "{{ $k }}", "{{ $v }}") where {{ $.datapoint_condition }}
              {{ end }}
            {{ end }}
            {{ if .metric_attribute_keys }}
            - context: datapoint
              statements:
              {{ range $k, $v := .metric_attribute_keys }}
              - replace_all_patterns(attributes, "key", "{{ $k }}", "{{ $v }}") where {{ $.datapoint_condition }}
              {{ end }}
            {{ end }}
      {{ end }}
      {{ end }}
  logs:
    processors: |
      {{ if .enable_logs }}
      {{ if or .log_resource_keys .log_attribute_keys .log_body_keys }}
      - transform/logs:
          error_mode: ignore
          log_statements:
            {{ if .log_resource_keys }}
            - context: log
              statements:
              {{ range $k, $v := .log_resource_keys }}
              - replace_all_patterns(resource.attributes, "key", "{{ $k }}", "{{ $v }}") where {{ $.log_condition }}
              {{ end }}
            {{ end }}
            {{ if .log_attribute_keys }}
            - context: log
              statements:
              {{ range $k, $v := .log_attribute_keys }}
              - replace_all_patterns(attributes, "key", "{{ $k }}", "{{ $v }}") where {{ $.log_condition }}
              {{ end }}
            {{ end }}
            {{ if .log_body_keys }}
            - context: log
              statements:
              {{ range $k, $v := .log_body_keys }}
              - replace_all_patterns(body, "key", "{{ $k }}", "{{ $v }}") where {{ $.log_condition }}
              {{ end }}
            {{ end }}
      {{ end }}
      {{ end }}
  traces:
    processors: |
      {{ if .enable_traces }}
      {{ if or .trace_resource_keys .trace_attribute_keys }}
      - transform/traces:
          error_mode: ignore
          trace_statements:
            {{ if .trace_resource_keys }}
            - context: span
              statements:
              {{ range $k, $v := .trace_resource_keys }}
              - replace_all_patterns(resource.attributes, "key", "{{ $k }}", "{{ $v }}") where {{ $.span_condition }}
              {{ end }}
            {{ end }}
            {{ if .trace_attribute_keys }}
            - context: span
              statements:
              {{ range $k, $v := .trace_attribute_keys }}
              - replace_all_patterns(attributes, "key", "{{ $k }}", "{{ $v }}") where {{ $.span_condition }}
              {{ end }}
            {{ end }}
      {{ end }}
      {{ end }}
