apiVersion: bindplane.observiq.com/v1
kind: ProcessorType
metadata:
  name: add_resource
  displayName: Add Resource Attribute
  description: Insert, update, or upsert resource attributes to metrics, traces, and logs.
  labels:
    category: Transform
  deprecated: true
  additionalInfo:
    message: This processor has been deprecated and replaced by the Add Field processor. While it will continue to function, it will no longer receive any enhancements and you should migrate to Add Fields.
    documentation:
      - text: Add Fields Processor
        url: https://docs.bindplane.observiq.com/docs/add-field
spec:
  version: 0.0.1
  parameters:
    - name: action
      label: Action
      type: enum
      description: |
        insert: Add resource if it does not exist.
        update: Update existing value.
        upsert: Insert or update.
      default: upsert
      validValues:
        - insert
        - update
        - upsert

    - name: resources
      label: Resources
      type: map
      required: true
      options:
        gridColumns: 12

    - name: telemetry_types
      label: Enable Telemetry
      type: enums
      description: "Select which types of telemetry you'd like to enable this processor for."
      validValues: ["Metrics", "Logs", "Traces"]
      default: ["Metrics", "Logs", "Traces"]

  metrics:
    processors: |
      {{ if has "Metrics" .telemetry_types }}
      - resource:
          attributes:
            {{ range $k, $v := .resources }}
            - key: '{{ $k }}'
              value: {{ $v }}
              action: {{ $.action }}
            {{ end }}
      {{ end }}
  logs:
    processors: |
      {{ if has "Logs" .telemetry_types }}
      - resource:
          attributes:
            {{ range $k, $v := .resources }}
            - key: '{{ $k }}'
              value: {{ $v }}
              action: {{ $.action }}
            {{ end }}
      {{ end }}
  traces:
    processors: |
      {{ if has "Traces" .telemetry_types }}
      - resource:
          attributes:
            {{ range $k, $v := .resources }}
            - key: '{{ $k }}'
              value: {{ $v }}
              action: {{ $.action }}
            {{ end }}
      {{ end }}
