// Code generated by mockery v2.31.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	server "github.com/observiq/bindplane-op/server"
)

// MockRouteBuilder is an autogenerated mock type for the RouteBuilder type
type MockRouteBuilder struct {
	mock.Mock
}

// AddRoutes provides a mock function with given fields: _a0, _a1
func (_m *MockRouteBuilder) AddRoutes(_a0 gin.IRouter, _a1 server.BindPlane) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(gin.IRouter, server.BindPlane) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRouteBuilder creates a new instance of MockRouteBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouteBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouteBuilder {
	mock := &MockRouteBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
