// Code generated by mockery v2.31.1. DO NOT EDIT.

package serve

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Seed provides a mock function with given fields: ctx
func (_m *MockServer) Seed(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServer_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type MockServer_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServer_Expecter) Seed(ctx interface{}) *MockServer_Seed_Call {
	return &MockServer_Seed_Call{Call: _e.mock.On("Seed", ctx)}
}

func (_c *MockServer_Seed_Call) Run(run func(ctx context.Context)) *MockServer_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServer_Seed_Call) Return(_a0 error) *MockServer_Seed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServer_Seed_Call) RunAndReturn(run func(context.Context) error) *MockServer_Seed_Call {
	_c.Call.Return(run)
	return _c
}

// Serve provides a mock function with given fields: ctx
func (_m *MockServer) Serve(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServer_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockServer_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServer_Expecter) Serve(ctx interface{}) *MockServer_Serve_Call {
	return &MockServer_Serve_Call{Call: _e.mock.On("Serve", ctx)}
}

func (_c *MockServer_Serve_Call) Run(run func(ctx context.Context)) *MockServer_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServer_Serve_Call) Return(_a0 error) *MockServer_Serve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServer_Serve_Call) RunAndReturn(run func(context.Context) error) *MockServer_Serve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
