name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: "1.20"

      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Cache Go
        id: module-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache NPM
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ui/node_modules
          key: npm-cache-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: npm-cache-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.9.0
          args: release --rm-dist --parallelism 1
        env:
          # github token requires permission to observiq/bindplane-op and observiq/homebrew-bindplane-op
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  readme:
    runs-on: "ubuntu-22.04"
    needs:
      - release
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      # Always publish to 1.0, as creating a new version
      # will cause IDs to change.
      - uses: readmeio/rdme@8.4.0
        name: Publish Docs to Readme
        with:
          rdme: docs ./docs/www --key=${{ secrets.README_API_KEY }} --version 1.0

      # Cleanup pages that were removed from docs/www directory.
      - uses: readmeio/rdme@8.4.0
        name: Publish Docs to Readme
        with:
          rdme: docs:prune ./docs/www --key=${{ secrets.README_API_KEY }} --version 1.0 --confirm
