// Code generated by mockery v2.21.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/observiq/bindplane-op/model"
	mock "github.com/stretchr/testify/mock"

	protocol "github.com/observiq/bindplane-op/internal/server/protocol"

	store "github.com/observiq/bindplane-op/internal/store"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

// Agent provides a mock function with given fields: ctx, agentID
func (_m *MockManager) Agent(ctx context.Context, agentID string) (*model.Agent, error) {
	ret := _m.Called(ctx, agentID)

	var r0 *model.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Agent, error)); ok {
		return rf(ctx, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Agent); ok {
		r0 = rf(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentUpdates provides a mock function with given fields: ctx, agent
func (_m *MockManager) AgentUpdates(ctx context.Context, agent *model.Agent) (*protocol.AgentUpdates, error) {
	ret := _m.Called(ctx, agent)

	var r0 *protocol.AgentUpdates
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Agent) (*protocol.AgentUpdates, error)); ok {
		return rf(ctx, agent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Agent) *protocol.AgentUpdates); ok {
		r0 = rf(ctx, agent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protocol.AgentUpdates)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Agent) error); ok {
		r1 = rf(ctx, agent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentVersion provides a mock function with given fields: ctx, version
func (_m *MockManager) AgentVersion(ctx context.Context, version string) (*model.AgentVersion, error) {
	ret := _m.Called(ctx, version)

	var r0 *model.AgentVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AgentVersion, error)); ok {
		return rf(ctx, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AgentVersion); ok {
		r0 = rf(ctx, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindPlaneConfiguration provides a mock function with given fields:
func (_m *MockManager) BindPlaneConfiguration() model.BindPlaneConfiguration {
	ret := _m.Called()

	var r0 model.BindPlaneConfiguration
	if rf, ok := ret.Get(0).(func() model.BindPlaneConfiguration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.BindPlaneConfiguration)
		}
	}

	return r0
}

// EnableProtocol provides a mock function with given fields: _a0
func (_m *MockManager) EnableProtocol(_a0 protocol.Protocol) {
	_m.Called(_a0)
}

// RequestReport provides a mock function with given fields: ctx, agentID, configuration
func (_m *MockManager) RequestReport(ctx context.Context, agentID string, configuration protocol.Report) error {
	ret := _m.Called(ctx, agentID, configuration)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, protocol.Report) error); ok {
		r0 = rf(ctx, agentID, configuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResourceStore provides a mock function with given fields:
func (_m *MockManager) ResourceStore() model.ResourceStore {
	ret := _m.Called()

	var r0 model.ResourceStore
	if rf, ok := ret.Get(0).(func() model.ResourceStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ResourceStore)
		}
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *MockManager) Start(ctx context.Context) {
	_m.Called(ctx)
}

// UpsertAgent provides a mock function with given fields: ctx, agentID, updater
func (_m *MockManager) UpsertAgent(ctx context.Context, agentID string, updater store.AgentUpdater) (*model.Agent, error) {
	ret := _m.Called(ctx, agentID, updater)

	var r0 *model.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, store.AgentUpdater) (*model.Agent, error)); ok {
		return rf(ctx, agentID, updater)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, store.AgentUpdater) *model.Agent); ok {
		r0 = rf(ctx, agentID, updater)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, store.AgentUpdater) error); ok {
		r1 = rf(ctx, agentID, updater)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifySecretKey provides a mock function with given fields: ctx, secretKey
func (_m *MockManager) VerifySecretKey(ctx context.Context, secretKey string) bool {
	ret := _m.Called(ctx, secretKey)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, secretKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewMockManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockManager(t mockConstructorTestingTNewMockManager) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
